import { Ticket, User, Worklog, AuditLog, IntegrationConfig, SyncLog, AppNotification, SLAPolicyConfig } from '@/types';
import { analyzeTicketWithRuleEngine } from './ruleEngine';

export const SEED_USERS: User[] = [
  {
    id: 'usr-ismailak',
    name: 'Ismail Akbar (ismailak)',
    username: 'ismailak',
    email: 'ismailak@lt-integra.com',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
    role: 'admin',
    isActive: true,
    department: 'DNS & DHCP Infoblox Engineering',
    lastLoginAt: '2026-09-07T21:00:00Z',
    password: 'ismailak1234',
  },
];

export const SEED_TICKETS: Ticket[] = [
  {
    id: 'tkt-otrs-32407',
    externalId: 'OTRS-2026090122000053',
    ticketNumber: '2026090122000053',
    kriteria: 'DNS Request',
    subKriteria: 'A Record',
    subject: "Fw: [MIGRASI DCI - Procsys] Permohonan Request DNS Database Procsys",
    description: `Fw: [MIGRASI DCI - Procsys] Permohonan Request DNS Database Procsys
[Article 72369]: P {margin-top:0;margin-bottom:0;} Dear rekan integra Tolong dibuatkan MOP terkait request berikut Terima kasih Best Regards Evelio Excellenta From: MUHAMMAD ZAKY RAFFINALDY &lt;m.zaky@bankbsi.co.id&gt; Sent: Monday, August 31, 2026 11:48 AM To: IOG CR Network &lt;iog_crnetwork@bankbsi.co.id&gt;; IOG Officer On Duty &lt;iog_monitoring@bankbsi.co.id&gt; Cc: FITRIANTI KAUTSAR &lt;fitrianti.kautsar@bankbsi.co.id&gt;; DONNY ANDRIANTO &lt;ven.donnyandri@bankbsi.co.id&gt;; DEWI AYUNAH &lt;dewi.ayunah@bankbsi.co.id&gt;; Dila Kiranti &lt;dila.kiranti@bankbsi.co.id&gt;; Puti Andini &lt;ven.andini@bankbsi.co.id&gt;; Syifa Lutfiah &lt;ven.lutfiah@bankbsi.co.id&gt;; HARIS KURNIAWAN &lt;haris.kurniawan@bankbsi.co.id&gt;; Azka Lazuardi Farghani &lt;azka.lazuardi@bankbsi.co.id&gt; Subject: [MIGRASI DCI - Procsys] Permohonan Request DNS Database Procsys &nbsp; Dear Tim Network - IOG Sehubungan akan dilaksanakan kembali DRP dan Migrasi DCl di tahun 2026, mohon bantuannya untuk dilakukan percepatan aktivitas berikut pada Aplikasi Procsys. 1. Request DNS DB Procsys (prosysdb.bankbsi.co.id) Izin berikut kami lampirkan juga memo dan form yang dibutuhkan. Terima kasih. Wassalamualaikum wr wb. Regards, Muhammad Zaky Raffinaldy IT ASP
[Article 72370]: Hello Customer, We have received your problem report and have created " [Ticket#2026090122000053] Fw: [MIGRASI DCI - Procsys] Permohonan Request DNS Database Procsys ". Your Ticket will be answered by a Team Support. Regards, Icare You wrote : Dear rekan integra Tolong dibuatkan MOP terkait request berikut Terima kasih Best Regards Evelio Excellenta ________________________________ From: MUHAMMAD ZAKY RAFFINALDY &lt;m.zaky@bankbsi.co.id&gt; Sent: Monday, August 31 ... [Content truncated for display]`,
    mainCategory: 'Service Request',
    technicalCategory: 'DNS',
    priority: 'MEDIUM',
    status: 'OPEN',
    requester: 'Bank Syariah Indonesia (BSI)',
    requesterEmail: 'bsi-ops@bankbsi.co.id',
    assigneeId: 'usr-03',
    assigneeName: 'Ismail Ak (ismailak)',
    assignmentGroup: 'OP0899 - BSI DNS & DHCP Infoblox',
    createdAt: '2026-09-07T08:00:00.000Z',
    updatedAt: '2026-09-07T12:00:00.000Z',
    dueAt: '2026-09-08T08:00:00.000Z',
    slaHours: 24,
    slaStatus: 'SAFE',
    ruleEngineSuggested: {
      mainCategory: 'Service Request',
      technicalCategory: 'DNS',
      priority: 'MEDIUM',
      confidence: 96,
      matchedKeywords: ["dns", "a record", "infoblox"],
      explanation: "Matched 'Penambahan DNS' request. Categorized as DNS Request -> Sub-kriteria: A Record.",
    },
  },
  {
    id: 'tkt-otrs-32409',
    externalId: 'OTRS-2026090122000071',
    ticketNumber: '2026090122000071',
    kriteria: 'DNS Request',
    subKriteria: 'CNAME',
    subject: "Fw: PENAMBAHAN DNS CNAME UNTUK APLIKASI IDEB DI DC CIBITUNG",
    description: `Fw: PENAMBAHAN DNS CNAME UNTUK APLIKASI IDEB DI DC CIBITUNG
[Article 72387]: P {margin-top:0;margin-bottom:0;} Dear rekan integra Tolong dibuatkan MOP terkait request berikut, eksekusi hari kamis Terima kasih Best Regards Evelio Excellenta From: ABNI SUKAJI YUSUF &lt;abni.sukaji@bankbsi.co.id&gt; Sent: Monday, August 31, 2026 8:50 PM To: IOG Network &lt;iog_network@bankbsi.co.id&gt;; IOG CR Network &lt;iog_crnetwork@bankbsi.co.id&gt; Cc: ROHADY WIBOWO &lt;rohady.wibowo@bankbsi.co.id&gt; Subject: PENAMBAHAN DNS CNAME UNTUK APLIKASI IDEB DI DC CIBITUNG &nbsp; Dear Team Network Mohon bantuannya dalam eksekusi FKK Penambahan DNS CNAME untuk aplikasi IDEB. Berikut merupakan fkk perkerjaan (terlampir) Terkait pengerjaan, akan dilakukan segera setelah mendapatkan approval dari tim CR (after office). Sudah berdiskusi dengan tim network, estimasi pengerjaan 5-10 menit. Perihal ini diajukan karena penambahan DNS CNAME pada server baru untuk persiapan migrasi aplikasi ke DC Cibitung. Pengerjaan tetap dapat dilakukan karena sudah ada nota eksepsi untuk kegiatan migrasi. Demikian informasi yang dapat saya sampaikan. Jika ada yang ditanyakan dapat membalas email ini ataupun chat melalui teams @ABNI SUKAJI YUSUF / @ROHADY WIBOWO . Terimakasih Best Regards -AB- Abni Sukaji Yusuf Infrastructure System and Optimization Analyst PT Bank Syariah Indonesia Tbk IT Operations Groups | IT Infrastructure Operations Management and Optimization BSI Tower, Jl. Medan Merdeka Selatan No. 17 +62 859-7725-3535 | abni.sukaji@bankbsi.co.id
[Article 72388]: Hello Customer, We have received your problem report and have created " [Ticket#2026090122000071] Fw: PENAMBAHAN DNS CNAME UNTUK APLIKASI IDEB DI DC CIBITUNG ". Your Ticket will be answered by a Team Support. Regards, Icare You wrote : Dear rekan integ ... [Content truncated for display]`,
    mainCategory: 'Service Request',
    technicalCategory: 'DNS',
    priority: 'MEDIUM',
    status: 'OPEN',
    requester: 'Bank Syariah Indonesia (BSI)',
    requesterEmail: 'bsi-ops@bankbsi.co.id',
    assigneeId: 'usr-03',
    assigneeName: 'Ismail Ak (ismailak)',
    assignmentGroup: 'OP0899 - BSI DNS & DHCP Infoblox',
    createdAt: '2026-09-07T08:00:00.000Z',
    updatedAt: '2026-09-07T12:00:00.000Z',
    dueAt: '2026-09-08T08:00:00.000Z',
    slaHours: 24,
    slaStatus: 'SAFE',
    ruleEngineSuggested: {
      mainCategory: 'Service Request',
      technicalCategory: 'DNS',
      priority: 'MEDIUM',
      confidence: 96,
      matchedKeywords: ["dns", "cname", "infoblox"],
      explanation: "Matched 'Penambahan DNS' request. Categorized as DNS Request -> Sub-kriteria: CNAME.",
    },
  },
  {
    id: 'tkt-otrs-32427',
    externalId: 'OTRS-2026090222000033',
    ticketNumber: '2026090222000033',
    kriteria: 'DNS Request',
    subKriteria: 'A Record',
    subject: "Fw: [Migrasi DCI - Go UMKM] Permohonan Request DNS Database Go UMKM",
    description: `Fw: [Migrasi DCI - Go UMKM] Permohonan Request DNS Database Go UMKM
[Article 72464]: P {margin-top:0;margin-bottom:0;} Untuk melindungi privasi Anda, konten jauh diblokir. Beban diblokir konten. Dear rekan integra Tolong dibuatkan MOP terkait request berikut Terima kasih Best Regards Evelio Excellenta From: Puti Andini &lt;ven.andini@bankbsi.co.id&gt; Sent: Friday, August 28, 2026 5:41 PM To: IOG CR Network &lt;iog_crnetwork@bankbsi.co.id&gt; Cc: DONNY ANDRIANTO &lt;ven.donnyandri@bankbsi.co.id&gt;; DEWI AYUNAH &lt;dewi.ayunah@bankbsi.co.id&gt;; Dila Kiranti &lt;dila.kiranti@bankbsi.co.id&gt;; FITRIANTI KAUTSAR &lt;fitrianti.kautsar@bankbsi.co.id&gt;; MUHAMMAD ZAKY RAFFINALDY &lt;m.zaky@bankbsi.co.id&gt;; FARALITA FAISAL &lt;faralita.faisal@bankbsi.co.id&gt;; Azka Lazuardi Farghani &lt;azka.lazuardi@bankbsi.co.id&gt;; HARIS KURNIAWAN &lt;haris.kurniawan@bankbsi.co.id&gt;; FAJAR IRIANTO PRAJOKO &lt;fajar.irianto@bankbsi.co.id&gt;; SUHENDRA WINATA &lt;suhendra.winata@bankbsi.co.id&gt;; Syifa Lutfiah &lt;ven.lutfiah@bankbsi.co.id&gt;; Ayasha Naila Ismunandar &lt;ayasha.naila@bankbsi.co.id&gt; Subject: [Migrasi DCI - Go UMKM] Permohonan Request DNS Database Go UMKM &nbsp; Dear Tim Network - IOG Sehubungan akan dilaksanakan kembali DRP dan Migrasi DCI di tahun 2026, mohon bantuannya untuk dilakukan percepatan aktivitas berikut pada Aplikasi Go UMKM. Request DNS DB GO UMKM (goumkmdb.bankbsi.co.id) Izin berikut kami lampirkan juga memo dan form yang dibutuhkan. ​ ​ 06. FKK Request DNS Database Go UMKM untuk Kebutuhan Migrasi Go UMKM.pdf ​ ​ Terima kasih. Wassalamualaikum wr wb. Regards, Puti Andini IT ASP
[Article 72465]: Hello Customer, We have received your problem report and have created " [Ticket#2026090222000033] Fw: [Migrasi DCI - Go UMKM] Permohonan Request DNS Database ... [Content truncated for display]`,
    mainCategory: 'Service Request',
    technicalCategory: 'DNS',
    priority: 'MEDIUM',
    status: 'OPEN',
    requester: 'Bank Syariah Indonesia (BSI)',
    requesterEmail: 'bsi-ops@bankbsi.co.id',
    assigneeId: 'usr-03',
    assigneeName: 'Ismail Ak (ismailak)',
    assignmentGroup: 'OP0899 - BSI DNS & DHCP Infoblox',
    createdAt: '2026-09-07T08:00:00.000Z',
    updatedAt: '2026-09-07T12:00:00.000Z',
    dueAt: '2026-09-08T08:00:00.000Z',
    slaHours: 24,
    slaStatus: 'SAFE',
    ruleEngineSuggested: {
      mainCategory: 'Service Request',
      technicalCategory: 'DNS',
      priority: 'MEDIUM',
      confidence: 96,
      matchedKeywords: ["dns", "a record", "infoblox"],
      explanation: "Matched 'Penambahan DNS' request. Categorized as DNS Request -> Sub-kriteria: A Record.",
    },
  },
  {
    id: 'tkt-otrs-32428',
    externalId: 'OTRS-2026090222000042',
    ticketNumber: '2026090222000042',
    kriteria: 'DNS Request',
    subKriteria: 'A Record',
    subject: "Fw: [Migrasi DCI - CMON] Permohonan Request DNS Database Aplikasi CMON",
    description: `Fw: [Migrasi DCI - CMON] Permohonan Request DNS Database Aplikasi CMON
[Article 72466]: P {margin-top:0;margin-bottom:0;} Dear rekan integra Tolong diguatkan MOP terkait request berikut Terima kasih Best Regards Evelio Excellenta From: Dila Kiranti &lt;dila.kiranti@bankbsi.co.id&gt; Sent: Monday, August 31, 2026 10:44 AM To: IOG CR Network &lt;iog_crnetwork@bankbsi.co.id&gt; Cc: IOG Network &lt;iog_network@bankbsi.co.id&gt;; DEWI AYUNAH &lt;dewi.ayunah@bankbsi.co.id&gt;; YAN ACHSRI &lt;yan.achsri@bankbsi.co.id&gt;; Azka Lazuardi Farghani &lt;azka.lazuardi@bankbsi.co.id&gt;; HARIS KURNIAWAN &lt;haris.kurniawan@bankbsi.co.id&gt;; DONNY ANDRIANTO &lt;ven.donnyandri@bankbsi.co.id&gt;; FITRIANTI KAUTSAR &lt;fitrianti.kautsar@bankbsi.co.id&gt;; SUHENDRA WINATA &lt;suhendra.winata@bankbsi.co.id&gt;; FARALITA FAISAL &lt;faralita.faisal@bankbsi.co.id&gt; Subject: [Migrasi DCI - CMON] Permohonan Request DNS Database Aplikasi CMON &nbsp; Selamat Pagi rekan-rekan IOG. Sehubungan akan dilaksanakan kembali DRP dan Migrasi DCI di tahun 2026, mohon bantuannya untuk dilakukan percepatan aktivitas berikut pada Aplikasi C-Mon. Request DNS DB C-Mon (c-mondb.bankbsi.co.id) Izin berikut kami lampirkan juga memo dan form yang dibutuhkan. Terima kasih. Wassalamualaikum wr wb. Regards, Dila Kiranti Release Management Officer | ASP
[Article 72467]: Hello Customer, We have received your problem report and have created " [Ticket#2026090222000042] Fw: [Migrasi DCI - CMON] Permohonan Request DNS Database Aplikasi CMON ". Your Ticket will be answered by a Team Support. Regards, Icare You wrote : Dear rekan integra Tolong diguatkan MOP terkait request berikut Terima kasih Best Regards Evelio Excellenta ________________________________ From: Dila Kiranti &lt;dila.kiranti@bankbsi.co.id&gt; Sent: Monday, ... [Content truncated for display]`,
    mainCategory: 'Service Request',
    technicalCategory: 'DNS',
    priority: 'MEDIUM',
    status: 'OPEN',
    requester: 'Bank Syariah Indonesia (BSI)',
    requesterEmail: 'bsi-ops@bankbsi.co.id',
    assigneeId: 'usr-03',
    assigneeName: 'Ismail Ak (ismailak)',
    assignmentGroup: 'OP0899 - BSI DNS & DHCP Infoblox',
    createdAt: '2026-09-07T08:00:00.000Z',
    updatedAt: '2026-09-07T12:00:00.000Z',
    dueAt: '2026-09-08T08:00:00.000Z',
    slaHours: 24,
    slaStatus: 'SAFE',
    ruleEngineSuggested: {
      mainCategory: 'Service Request',
      technicalCategory: 'DNS',
      priority: 'MEDIUM',
      confidence: 96,
      matchedKeywords: ["dns", "a record", "infoblox"],
      explanation: "Matched 'Penambahan DNS' request. Categorized as DNS Request -> Sub-kriteria: A Record.",
    },
  },
  {
    id: 'tkt-otrs-32445',
    externalId: 'OTRS-2026090322000059',
    ticketNumber: '2026090322000059',
    kriteria: 'DRP',
    subKriteria: 'Standby Onsite (Go UMKM)',
    subject: "Request Engineer onsite untuk Support DRP Go UMKM 03 September 2026",
    description: `Request Engineer onsite untuk Support DRP Go UMKM 03 September 2026
[Article 72511]: P {margin-top:0;margin-bottom:0;} Dear rekan Integra Tolong dialokasikan engineer on site untuk support kegiatan DRP pada hari Rabu, 3 September 2026 sebagai berikut: DRP Go UMKM Pukul : 10.30- Selesai Aktivitas:&nbsp; Ubah Pointing DNS (go-umkm.bankbsi.co.id) - dari 10.0.96.53 ke 10.216.249.231 Terima Kasih Best Regards, Haykal Atthoriq B - Network Management Engineer IT Operations Group (IOG) &nbsp; M &nbsp; :&nbsp;+6282131321204&nbsp; E &nbsp;&nbsp;&nbsp;: haykal.atthoriq@bankbsi.co.id &nbsp; W &nbsp;: www.bankbsi.co.id &nbsp; PT. Bank Syariah Indonesia (Persero), Tbk.&nbsp;| Kantor Pusat Gedung BSI Tower&nbsp;| Jl. Medan Merdeka Sel. No.17 Lt. 18, Daerah Khusus Ibukota Jakarta 10110
[Article 72512]: Hello Customer, We have received your problem report and have created " [Ticket#2026090322000059] Request Engineer onsite untuk Support DRP Go UMKM 03 September 2026 ". Your Ticket will be answered by a Team Support. Regards, Icare You wrote : Dear rekan Integra Tolong dialokasikan engineer on site untuk support kegiatan DRP pada hari Rabu, 3 September 2026 sebagai berikut: DRP Go UMKM Pukul : 10.30- Selesai Aktivitas: Ubah Pointing DNS (go-umkm.bankbsi.co.id) - dari 10.0.96.53 ke 10.216.249.231 Terima Kasih Best Regards, Haykal Atthoriq B - Network Management Engineer IT Operations Group (IOG) [cid:e73f2780-8325-4a5d-926a-f9548c0cf303] M : +6282131321204 P.S. : To view the update, please login to Integra Care on&nbsp; https://icare.lt-integra.com/`,
    mainCategory: 'Change Request',
    technicalCategory: 'Network',
    priority: 'MEDIUM',
    status: 'OPEN',
    requester: 'Bank Syariah Indonesia (BSI)',
    requesterEmail: 'bsi-ops@bankbsi.co.id',
    assigneeId: 'usr-03',
    assigneeName: 'Ismail Ak (ismailak)',
    assignmentGroup: 'OP0899 - BSI DNS & DHCP Infoblox',
    createdAt: '2026-09-07T08:00:00.000Z',
    updatedAt: '2026-09-07T12:00:00.000Z',
    dueAt: '2026-09-08T08:00:00.000Z',
    slaHours: 24,
    slaStatus: 'SAFE',
    ruleEngineSuggested: {
      mainCategory: 'Change Request',
      technicalCategory: 'Network',
      priority: 'MEDIUM',
      confidence: 96,
      matchedKeywords: ["standby", "drp", "onsite"],
      explanation: "Matched engineer standby onsite for Disaster Recovery. Categorized as DRP -> Standby Onsite (Go UMKM).",
    },
  },
  {
    id: 'tkt-otrs-32446',
    externalId: 'OTRS-2026090322000068',
    ticketNumber: '2026090322000068',
    kriteria: 'Reserve IP',
    subKriteria: 'Reserve IP',
    subject: "Fw: RESERVE IP (IOG NETWORK)",
    description: `Fw: RESERVE IP (IOG NETWORK)
[Article 72513]: Dear rekan integra Tolong reserve IP berikut Terimakasih&nbsp; Best Regards&nbsp; Evelio Excellenta&nbsp; Get Outlook for Android From: ADI KURNIAWAN. &lt;adi.kurniawan19095@bankbsi.co.id&gt; Sent: Thursday, 03 September 2026 09:08:31 To: IOG Network &lt;iog_network@bankbsi.co.id&gt; Cc: Agus Ramadhany &lt;agus.ramadhany@bankbsi.co.id&gt; Subject: RESERVE IP (IOG NETWORK) &nbsp; IP Lama :&nbsp; 10.3.140.7 IP Reserve &nbsp; &nbsp;: 10.3.140.7 MacAddress : 14-D4-24-32-32-2F Hostname &nbsp; &nbsp;: NB-CBG-ADIKUR Best Regards Adi Kurniawan Process &amp; System Improvement|Card Business Group| Bank Syariah Indonesia Tbk The Tower Build. 26 th &nbsp;Floor Jl.Jend.Gatot Subroto Kav.11 Jakarta Selatan
[Article 72514]: Hello Customer, We have received your problem report and have created " [Ticket#2026090322000068] Fw: RESERVE IP (IOG NETWORK) ". Your Ticket will be answered by a Team Support. Regards, Icare You wrote : Dear rekan integra Tolong reserve IP berikut Terimakasih Best Regards Evelio Excellenta Get Outlook for Android&lt; https://aka.ms/AAb9ysg &gt; ________________________________ From: ADI KURNIAWAN. &lt;adi.kurniawan19095@bankbsi.co.id&gt; Sent: Thursday, 03 September 2026 09:08:31 To: IOG Network &lt;iog_network@bankbsi.co.id&gt; Cc: Agus Ramadhany &lt;agus.ramadhany@bankbsi.co.id&gt; Subject: RESERVE IP (IOG NETWORK) IP Lama : 10.3.140.7 IP Reserve : 10.3.140.7 MacAddress : 14-D4-24-32-32-2F Hostname : NB-CBG-ADIKUR P.S. : To view the update, please login to Integra Care on&nbsp; https://icare.lt-integra.com/
[Article 72518]: P {margin-top:0;margin-bottom:0;} Dear Rekan, Terkait requestnya sudah pernah di request dan suda di eksekusi, Berikut terlampir Juga Reportnya : Demikian Yang Dapat Diinformasikan, Terimakasih  ... [Content truncated for display]`,
    mainCategory: 'Incident',
    technicalCategory: 'DHCP',
    priority: 'MEDIUM',
    status: 'OPEN',
    requester: 'Bank Syariah Indonesia (BSI)',
    requesterEmail: 'bsi-ops@bankbsi.co.id',
    assigneeId: 'usr-03',
    assigneeName: 'Ismail Ak (ismailak)',
    assignmentGroup: 'OP0899 - BSI DNS & DHCP Infoblox',
    createdAt: '2026-09-07T08:00:00.000Z',
    updatedAt: '2026-09-07T12:00:00.000Z',
    dueAt: '2026-09-08T08:00:00.000Z',
    slaHours: 24,
    slaStatus: 'SAFE',
    ruleEngineSuggested: {
      mainCategory: 'Incident',
      technicalCategory: 'DHCP',
      priority: 'MEDIUM',
      confidence: 96,
      matchedKeywords: ["reserve ip", "dhcp", "reservation"],
      explanation: "Matched 'Reserve IP / Fixed Address' in ticket. Categorized as Reserve IP -> Reserve IP.",
    },
  },
  {
    id: 'tkt-otrs-32448',
    externalId: 'OTRS-2026090322000086',
    ticketNumber: '2026090322000086',
    kriteria: 'DRP',
    subKriteria: 'Standby Onsite (Procsyst)',
    subject: "Request Engineer onsite untuk Support DRP Procsyst 03 September 2026",
    description: `Request Engineer onsite untuk Support DRP Procsyst 03 September 2026
[Article 72516]: P {margin-top:0;margin-bottom:0;} Dear rekan integra Tolong dialokasikan engineer on site untuk support kegiatan DRP pada hari Rabu, 3 September 2026 sebagai berikut: DRP Procsyst Pukul : 18.00- Selesai Aktivitas:&nbsp; Ubah Pointing DNS&nbsp;10.0.17.127&nbsp;--&gt;&nbsp;10.216.249.122 Procsyst.bankbsi.co.id &nbsp; vendormgt.bankbsi.co.id Terima kasih Best Regards Evelio Excellenta
[Article 72517]: Hello Customer, We have received your problem report and have created " [Ticket#2026090322000086] Request Engineer onsite untuk Support DRP Procsyst 03 September 2026 ". Your Ticket will be answered by a Team Support. Regards, Icare You wrote : Dear rekan integra Tolong dialokasikan engineer on site untuk support kegiatan DRP pada hari Rabu, 3 September 2026 sebagai berikut: DRP Procsyst Pukul : 18.00- Selesai Aktivitas: Ubah Pointing DNS 10.0.17.127 --&gt; 10.216.249.122 * Procsyst.bankbsi.co.id * vendormgt.bankbsi.co.id Terima kasih P.S. : To view the update, please login to Integra Care on&nbsp; https://icare.lt-integra.com/`,
    mainCategory: 'Change Request',
    technicalCategory: 'Network',
    priority: 'MEDIUM',
    status: 'OPEN',
    requester: 'Bank Syariah Indonesia (BSI)',
    requesterEmail: 'bsi-ops@bankbsi.co.id',
    assigneeId: 'usr-03',
    assigneeName: 'Ismail Ak (ismailak)',
    assignmentGroup: 'OP0899 - BSI DNS & DHCP Infoblox',
    createdAt: '2026-09-07T08:00:00.000Z',
    updatedAt: '2026-09-07T12:00:00.000Z',
    dueAt: '2026-09-08T08:00:00.000Z',
    slaHours: 24,
    slaStatus: 'SAFE',
    ruleEngineSuggested: {
      mainCategory: 'Change Request',
      technicalCategory: 'Network',
      priority: 'MEDIUM',
      confidence: 96,
      matchedKeywords: ["standby", "drp", "onsite"],
      explanation: "Matched engineer standby onsite for Disaster Recovery. Categorized as DRP -> Standby Onsite (Procsyst).",
    },
  },
  {
    id: 'tkt-otrs-32449',
    externalId: 'OTRS-2026090322000095',
    ticketNumber: '2026090322000095',
    kriteria: 'Reserve IP',
    subKriteria: 'Reserve IP',
    subject: "Fw: Permohonan Reserve IP Private dan SafeConnect User Lt23 BSI Tower",
    description: `Fw: Permohonan Reserve IP Private dan SafeConnect User Lt23 BSI Tower
[Article 72520]: Dear rekan integra&nbsp; Tolong reserve IP address berikut Terimakasih&nbsp; Best Regards&nbsp; Evelio Excellenta&nbsp; Get Outlook for Android From: NAHARI RASIF &lt;nahari.rasif@bankbsi.co.id&gt; Sent: Thursday, 03 September 2026 12:37:34 To: FACHRI AKBAR RASFANZANI &lt;fachri.akbar@bankbsi.co.id&gt;; Evelio Excellenta &lt;evelio.excellenta@bankbsi.co.id&gt; Cc: AMNI ALFIRA &lt;amni.alfira@bankbsi.co.id&gt; Subject: Permohonan Reserve IP Private dan SafeConnect User Lt23 BSI Tower &nbsp; Assalamualaikum Wr Wb Dear Mas @FACHRI AKBAR RASFANZANI dan @Evelio Excellenta Terkait dengan adanya penambahan device handphone baru untuk beberapa MSA, dibutuhkan reserve IP PrivateConnect di Lt 23 BSI Tower. Mohon dibantu untuk dilakukan reserve IP dengan user berikut: PrivateConnect No Nama LDAP Jenis HP Mac Address Static Reserved IP 1 Achmad Yulianto evo_achmad.yulianto Samsung Flip 7 bcb2ccf7d264 10.2.80.47 2 Achmad Yulianto evo_achmad.yulianto Realme 3 ae43346b5bf8 10.2.80.80 3 HANIFAH PRITASARI hanifah.pritasari Iphone 8 5C0947562C9E 10.2.80.86 4 HANIFAH PRITASARI hanifah.pritasari Galaxy A34 5G 98B08BFEB1E2 10.2.80.114 5 Wahyu Adam wahyu.adam Samsung Z Fold 6 BCB2CC117299 10.2.80.115 6 REZKI Rahman rezki.rahman iPhone 15 Pro Max 50B1272FC51D 10.2.80.121 7 Fakhri Martua fakhri.martua Vivo V23 5G d463de52474f 10.2.80.174 8 Alditama Sena alditama.sena iPhone 17 Pro 30E04F6E8CC7 10.2.80.175 9 Dhimas Pamungkas Wicaksono ven.dhimaspam Iphone 11 30E04F6E8CC7 10.2.80.176 10 Dhimas Pamungkas Wicaksono ven.dhimaspam Samsung Z Fold 6 BCB2CC11461E 10.2.80.177 Adapun untuk beberapa pihak organik untuk direserve IP SafeConnect, yaitu data user pada tabel berikut SafeConnect No Nama LDAP Jenis HP Mac Add ... [Content truncated for display]`,
    mainCategory: 'Service Request',
    technicalCategory: 'DHCP',
    priority: 'MEDIUM',
    status: 'OPEN',
    requester: 'Bank Syariah Indonesia (BSI)',
    requesterEmail: 'bsi-ops@bankbsi.co.id',
    assigneeId: 'usr-03',
    assigneeName: 'Ismail Ak (ismailak)',
    assignmentGroup: 'OP0899 - BSI DNS & DHCP Infoblox',
    createdAt: '2026-09-07T08:00:00.000Z',
    updatedAt: '2026-09-07T12:00:00.000Z',
    dueAt: '2026-09-08T08:00:00.000Z',
    slaHours: 24,
    slaStatus: 'SAFE',
    ruleEngineSuggested: {
      mainCategory: 'Service Request',
      technicalCategory: 'DHCP',
      priority: 'MEDIUM',
      confidence: 96,
      matchedKeywords: ["reserve ip", "dhcp", "reservation"],
      explanation: "Matched 'Reserve IP / Fixed Address' in ticket. Categorized as Reserve IP -> Reserve IP.",
    },
  },
  {
    id: 'tkt-otrs-32458',
    externalId: 'OTRS-2026090322000184',
    ticketNumber: '2026090322000184',
    kriteria: 'Reserve IP',
    subKriteria: 'Reserve IP',
    subject: "Re: Permohonan Reserve IP Device Project NEOM 2.0",
    description: `Re: Permohonan Reserve IP Device Project NEOM 2.0
[Article 72548]: P {margin-top:0;margin-bottom:0;} Dear Rekan Berikut terlampir hasil Reserve IP sesuai request : Sebagian IP sudah pernah di Reserve Demikian saya sampaikan Terima kasih Best Regard From: AZZAHRA NADYA KAHPIASA &lt;azzahra.nadya@bankbsi.co.id&gt; Sent: Thursday, September 3, 2026 5:27 PM To: Mochamad Sonda Nur Pasha &lt;mochamad.sonda@lt-integra.com&gt;; Ismail Akbar &lt;ismail.akbar@lt-integra.com&gt;; bsidnsdhcpsupp &lt;bsidnsdhcpsupp@lt-integra.com&gt; Cc: IOG Network &lt;iog_network@bankbsi.co.id&gt; Subject: Fw: Permohonan Reserve IP Device Project NEOM 2.0 &nbsp; Dear rekan Integra, Tolong di reserved list ip terlampir dan sertakan MOP Terima kasih Best Regards, Azzahra Nadya Kahpiasa HO &amp; Branch IT Facilities Engineer PT Bank Syariah Indonesia Tbk BSI Tower, Jl. Medan Merdeka Sel. No.17 Lt.18. Jakarta Pusat 10110 From: Muhammad Geluntung Wafi &lt;muhammad.geluntung@bankbsi.co.id&gt; Sent: 03 September 2026 15:48 To: IOG Network &lt;iog_network@bankbsi.co.id&gt; Cc: SANDY PRASETYA HADI &lt;sandy.prasetya@bankbsi.co.id&gt;; ARRY RINALDY PRATAMA &lt;arry.rinaldy@bankbsi.co.id&gt;; RICKY MAHENDRA &lt;ricky.mahendra@bankbsi.co.id&gt; Subject: Permohonan Reserve IP Device Project NEOM 2.0 &nbsp; Assalamualaikum Wr. Wb. Dear Tim IOG Network, Sehubungan dengan penggunaan device baru di gedung Danareksa perihal kebutuhan development project NEOM 2.0, mohon bantuannya untuk melakukan reserve IP pada device dengan data IP Address, MAC Address, dan Hostname sebagaimana terlampir di bawah. Mohon dapat diproses. Terima kasih atas bantuan dan kerja samanya. Wassalamualaikum Wr. Wb. Regards, Muhammad Geluntung Wafi No. IP Address MAC Address Hostname 1 10.2.213.72 F8:FF:C2:0B:49:65 MAC-IDG-SUMINI 2 10.2.215.3 ... [Content truncated for display]`,
    mainCategory: 'Service Request',
    technicalCategory: 'DHCP',
    priority: 'MEDIUM',
    status: 'OPEN',
    requester: 'Bank Syariah Indonesia (BSI)',
    requesterEmail: 'bsi-ops@bankbsi.co.id',
    assigneeId: 'usr-03',
    assigneeName: 'Ismail Ak (ismailak)',
    assignmentGroup: 'OP0899 - BSI DNS & DHCP Infoblox',
    createdAt: '2026-09-07T08:00:00.000Z',
    updatedAt: '2026-09-07T12:00:00.000Z',
    dueAt: '2026-09-08T08:00:00.000Z',
    slaHours: 24,
    slaStatus: 'SAFE',
    ruleEngineSuggested: {
      mainCategory: 'Service Request',
      technicalCategory: 'DHCP',
      priority: 'MEDIUM',
      confidence: 96,
      matchedKeywords: ["reserve ip", "dhcp", "reservation"],
      explanation: "Matched 'Reserve IP / Fixed Address' in ticket. Categorized as Reserve IP -> Reserve IP.",
    },
  },
  {
    id: 'tkt-otrs-32459',
    externalId: 'OTRS-2026090322000193',
    ticketNumber: '2026090322000193',
    kriteria: 'Reserve IP',
    subKriteria: 'Reserve IP',
    subject: "Re: Reserved IP",
    description: `Re: Reserved IP
[Article 72550]: P {margin-top:0;margin-bottom:0;} Dear Rekan Berikut terlampir hasil Reserve IP sesuai request : Demikian saya sampaikan Terima kasih Best Regard From: AZZAHRA NADYA KAHPIASA &lt;azzahra.nadya@bankbsi.co.id&gt; Sent: Thursday, September 3, 2026 5:28 PM To: Mochamad Sonda Nur Pasha &lt;mochamad.sonda@lt-integra.com&gt;; Ismail Akbar &lt;ismail.akbar@lt-integra.com&gt;; bsidnsdhcpsupp &lt;bsidnsdhcpsupp@lt-integra.com&gt; Cc: IOG Network &lt;iog_network@bankbsi.co.id&gt; Subject: Fw: Reserved IP &nbsp; Dear rekan Integra, Tolong reserved ip terlampir dan sertakan MOP Terima kasih&nbsp; Best Regards, Azzahra Nadya Kahpiasa HO &amp; Branch IT Facilities Engineer PT Bank Syariah Indonesia Tbk BSI Tower, Jl. Medan Merdeka Sel. No.17 Lt.18. Jakarta Pusat 10110 From: FAUZIA NUR FITRIA &lt;fauzia.nur1@bankbsi.co.id&gt; Sent: 03 September 2026 15:45 To: IOG Network &lt;iog_network@bankbsi.co.id&gt; Subject: Reserved IP &nbsp; Assalamualaikum wr.wb. Mohon bantuannya kepada tim IOG Network untuk bisa reserved beberapa IP berikut ini : IP Address Mac Address Hostname Jenis Device 10.2.205.197 58-02-05-94-31-08 NB-ASP-VENRHMAN Laptop Acer 10.2.212.100 58-02-05-94-10-AA NB-DBR-VENDAMAR Laptop Acer Atas perhatiannya terimakasih banyak �
[Article 72551]: Hello Customer, We have received your problem report and have created " [Ticket#2026090322000193] Re: Reserved IP ". Your Ticket will be answered by a Team Support. Regards, Icare You wrote : Dear Rekan Berikut terlampir hasil Reserve IP sesuai request : [cid:d95505c7-ab1b-418c-9a58-37e3cfab9e5c] Demikian saya sampaikan Terima kasih Best Regard P.S. : To view the update, please login to Integra Care on&nbsp; https://icare.lt-integra.com/`,
    mainCategory: 'Incident',
    technicalCategory: 'DHCP',
    priority: 'MEDIUM',
    status: 'OPEN',
    requester: 'Bank Syariah Indonesia (BSI)',
    requesterEmail: 'bsi-ops@bankbsi.co.id',
    assigneeId: 'usr-03',
    assigneeName: 'Ismail Ak (ismailak)',
    assignmentGroup: 'OP0899 - BSI DNS & DHCP Infoblox',
    createdAt: '2026-09-07T08:00:00.000Z',
    updatedAt: '2026-09-07T12:00:00.000Z',
    dueAt: '2026-09-08T08:00:00.000Z',
    slaHours: 24,
    slaStatus: 'SAFE',
    ruleEngineSuggested: {
      mainCategory: 'Incident',
      technicalCategory: 'DHCP',
      priority: 'MEDIUM',
      confidence: 96,
      matchedKeywords: ["reserve ip", "dhcp", "reservation"],
      explanation: "Matched 'Reserve IP / Fixed Address' in ticket. Categorized as Reserve IP -> Reserve IP.",
    },
  },
  {
    id: 'tkt-otrs-32461',
    externalId: 'OTRS-2026090322000219',
    ticketNumber: '2026090322000219',
    kriteria: 'DRP',
    subKriteria: 'Standby Onsite (WISE)',
    subject: "Support Engineer DRP WISE",
    description: `Support Engineer DRP WISE
[Article 72555]: P {margin-top:0;margin-bottom:0;} Assalamu'alaikum, Dear rekan integra Tolong dialokasikan engineer on site untuk support kegiatan&nbsp;DRP&nbsp;pada hari Jum'at, 4 September 2026 sebagai berikut: DRP WISE Pukul : 20.00- 05.00 Aktivitas:&nbsp; Ubah Pointing DNS&nbsp;10.0.142.22&nbsp;--&gt;&nbsp;10.222.8.109 wise.bankbsi.co.id &nbsp; sekian dan terima kasih. Wassalam Best Regards, Ramadhana Fitryanto Core Network, Extranet &amp; Internet Officer M: (+62) 822-7506-4382 E : ramadhana.fitryanto@bankbsi.co.id W: www.bankbsi.co.id PT. Bank Syariah Indonesia, Tbk. | Kantor Pusat Gedung The Tower | Jl. Gatot Subroto No. 27 Kelurahan Karet Semanggi, Kecamatan Setiabudi, Jakarta Selatan, DKI Jakarta 12930 Indonesia
[Article 72556]: Hello Customer, We have received your problem report and have created " [Ticket#2026090322000219] Support Engineer DRP WISE ". Your Ticket will be answered by a Team Support. Regards, Icare You wrote : Assalamu'alaikum, Dear rekan integra Tolong dialokasikan engineer on site untuk support kegiatan DRP pada hari Jum'at, 4 September 2026 sebagai berikut: DRP WISE Pukul : 20.00- 05.00 Aktivitas: Ubah Pointing DNS 10.0.142.22 --&gt; 10.222.8.109 * wise.bankbsi.co.id sekian dan terima kasih. Wassalam Best Regards, Ramadhana Fitryanto Core Network, Extranet &amp; Internet Officer P.S. : To view the update, please login to Integra Care on&nbsp; https://icare.lt-integra.com/
[Article 72577]: Add @Selamet Catur and @Budhy Santoso in the loop. &nbsp; Dear mas Rama, &nbsp; Terimakasih atas informasi yang diberikan. &nbsp; Regards, &nbsp; &nbsp; Hendik &nbsp; From: RAMADHANA FITRYANTO &lt;ramadhana.fitryanto@bankbsi.co.id&gt; Sent: 03 September 2026 19:05 To: bsidnsdhcp-support &lt;bsidnsdhcp-support@lt-integra.com&gt;; b ... [Content truncated for display]`,
    mainCategory: 'Change Request',
    technicalCategory: 'Network',
    priority: 'MEDIUM',
    status: 'OPEN',
    requester: 'Bank Syariah Indonesia (BSI)',
    requesterEmail: 'bsi-ops@bankbsi.co.id',
    assigneeId: 'usr-03',
    assigneeName: 'Ismail Ak (ismailak)',
    assignmentGroup: 'OP0899 - BSI DNS & DHCP Infoblox',
    createdAt: '2026-09-07T08:00:00.000Z',
    updatedAt: '2026-09-07T12:00:00.000Z',
    dueAt: '2026-09-08T08:00:00.000Z',
    slaHours: 24,
    slaStatus: 'SAFE',
    ruleEngineSuggested: {
      mainCategory: 'Change Request',
      technicalCategory: 'Network',
      priority: 'MEDIUM',
      confidence: 96,
      matchedKeywords: ["standby", "drp", "onsite"],
      explanation: "Matched engineer standby onsite for Disaster Recovery. Categorized as DRP -> Standby Onsite (WISE).",
    },
  },
  {
    id: 'tkt-otrs-32482',
    externalId: 'OTRS-2026090422000057',
    ticketNumber: '2026090422000057',
    kriteria: 'Reserve IP',
    subKriteria: 'Reserve IP',
    subject: "Re: Permohonan Reserve IP NB-CSO-BINTANG",
    description: `Re: Permohonan Reserve IP NB-CSO-BINTANG
[Article 72583]: P {margin-top:0;margin-bottom:0;} Dear Rekan, Terkait requestnya sudah selesai di eksekusi, Berikut terlampir MOP dan Juga Reportnya : Demikian Yang Dapat Diinformasikan, Terimakasih dan Best Regards, &nbsp; Mochamad Sonda Nur Pasha &nbsp; From: AZZAHRA NADYA KAHPIASA &lt;azzahra.nadya@bankbsi.co.id&gt; Sent: Friday, September 4, 2026 2:08 PM To: Mochamad Sonda Nur Pasha &lt;mochamad.sonda@lt-integra.com&gt;; Ismail Akbar &lt;ismail.akbar@lt-integra.com&gt;; bsidnsdhcpsupp &lt;bsidnsdhcpsupp@lt-integra.com&gt; Cc: IOG Network &lt;iog_network@bankbsi.co.id&gt; Subject: Fw: Permohonan Reserve IP NB-CSO-BINTANG &nbsp; Dear rekan integra, Tolong di reserved ip berikut Terima kasih&nbsp; Best Regards, Azzahra Nadya Kahpiasa HO &amp; Branch IT Facilities Engineer PT Bank Syariah Indonesia Tbk BSI Tower, Jl. Medan Merdeka Sel. No.17 Lt.18. Jakarta Pusat 10110 From: BINTANG PRAKASA ANTOVIE &lt;bintang.prakasa@bankbsi.co.id&gt; Sent: 04 September 2026 14:06 To: IOG Network &lt;iog_network@bankbsi.co.id&gt; Cc: ACHMAD RIYANDIKA ZAZULY &lt;achmad.riyandika@bankbsi.co.id&gt; Subject: Permohonan Reserve IP NB-CSO-BINTANG &nbsp; Assalamualaikum Wr. Wb. Dear tim IOG Network, Mohon bantuannya melakukan reserve IP dengan detail sebagai berikut: Mac address: C0-BF-BE-D1-9E-60 IP Address: 10.2.60.193 Hostname: NB-CSO-BINTANG Mohon bantuannya untuk kebutuhan tersebut. Terima kasih atas bantuan dan kerja samanya. Regards,&nbsp; Bintang Prakasa Antovie Sec. Red Teaming Officer | Sec. Assurance Dept. CISO Office Group
[Article 72584]: Hello Customer, We have received your problem report and have created " [Ticket#2026090422000057] Re: Permohonan Reserve IP NB-CSO-BINTANG ". Your Ticket will be answered by a Team Support. Regards, Icare ... [Content truncated for display]`,
    mainCategory: 'Service Request',
    technicalCategory: 'DHCP',
    priority: 'MEDIUM',
    status: 'OPEN',
    requester: 'Bank Syariah Indonesia (BSI)',
    requesterEmail: 'bsi-ops@bankbsi.co.id',
    assigneeId: 'usr-03',
    assigneeName: 'Ismail Ak (ismailak)',
    assignmentGroup: 'OP0899 - BSI DNS & DHCP Infoblox',
    createdAt: '2026-09-07T08:00:00.000Z',
    updatedAt: '2026-09-07T12:00:00.000Z',
    dueAt: '2026-09-08T08:00:00.000Z',
    slaHours: 24,
    slaStatus: 'SAFE',
    ruleEngineSuggested: {
      mainCategory: 'Service Request',
      technicalCategory: 'DHCP',
      priority: 'MEDIUM',
      confidence: 96,
      matchedKeywords: ["reserve ip", "dhcp", "reservation"],
      explanation: "Matched 'Reserve IP / Fixed Address' in ticket. Categorized as Reserve IP -> Reserve IP.",
    },
  },
  {
    id: 'tkt-otrs-32483',
    externalId: 'OTRS-2026090422000066',
    ticketNumber: '2026090422000066',
    kriteria: 'Reserve IP',
    subKriteria: 'Static IP',
    subject: "Fw: Permintaan Reservasi IP Khusus (Static IP) untuk Laptop Tim Digital Resource (Untuk Keperluan Open Akses oleh CISO)",
    description: `Fw: Permintaan Reservasi IP Khusus (Static IP) untuk Laptop Tim Digital Resource (Untuk Keperluan Open Akses oleh CISO)
[Article 72587]: P {margin-top:0;margin-bottom:0;} Dear rekan Integra, Mohon bantuannya untuk dibuatkan MoP dan eksekusi terkait reserve ip berikut. Best Regards, Bagas Pratama A Network Management Engineer E : bagas.pratama@bankbsi.co.id W: www.bankbsi.co.id PT. Bank Syariah Indonesia, Tbk. &nbsp; | Kantor Pusat Gedung The Tower &nbsp; | Jl. Gatot Subroto No. 27 Kelurahan Karet Semanggi, Kecamatan Setiabudi, Jakarta Selatan, DKI Jakarta 12930 Indonesia From: HARI NOVFERDIANTO &lt;hari.novferdianto@bankbsi.co.id&gt; Sent: Friday, September 4, 2026 10:03 AM To: IOG Network &lt;iog_network@bankbsi.co.id&gt; Cc: ALTEA SABILA &lt;altea.sabila@bankbsi.co.id&gt; Subject: Permintaan Reservasi IP Khusus (Static IP) untuk Laptop Tim Digital Resource (Untuk Keperluan Open Akses oleh CISO) &nbsp; Assalamualaikum Team IOG,&nbsp; Kami dari Enablement Department (IDG) ingin menyampaikan permintaan terkait reservasi IP address &nbsp;statis untuk beberapa laptop yang digunakan oleh anggota tim kami. Detail Permintaan: Tujuan Utama: &nbsp;Reservasi IP address &nbsp;statis untuk keperluan konfigurasi Open Koneksi &nbsp;oleh tim CISO ke beberapa endpoint &nbsp;spesifik yang memerlukan akses internet. Kebutuhan : &nbsp;Kegiatan harian Tim Digital Resource sangat bergantung pada koneksi ke endpoint &nbsp;yang kami minta. Kegagalan atau keterlambatan dalam akses ini akan secara langsung menghambat kelancaran pekerjaan dan kegiatan operasional . Oleh karena itu, kami memohon agar permintaan ini dapat diproses secepatnya. Dampak Kerja: &nbsp;Permintaan ini krusial demi memastikan kelancaran daily activity &nbsp;Tim Digital Resource, seperti technical test, dll. Berikut melamp ... [Content truncated for display]`,
    mainCategory: 'Incident',
    technicalCategory: 'DHCP',
    priority: 'MEDIUM',
    status: 'OPEN',
    requester: 'Bank Syariah Indonesia (BSI)',
    requesterEmail: 'bsi-ops@bankbsi.co.id',
    assigneeId: 'usr-03',
    assigneeName: 'Ismail Ak (ismailak)',
    assignmentGroup: 'OP0899 - BSI DNS & DHCP Infoblox',
    createdAt: '2026-09-07T08:00:00.000Z',
    updatedAt: '2026-09-07T12:00:00.000Z',
    dueAt: '2026-09-08T08:00:00.000Z',
    slaHours: 24,
    slaStatus: 'SAFE',
    ruleEngineSuggested: {
      mainCategory: 'Incident',
      technicalCategory: 'DHCP',
      priority: 'MEDIUM',
      confidence: 96,
      matchedKeywords: ["reserve ip", "dhcp", "reservation"],
      explanation: "Matched 'Reserve IP / Fixed Address' in ticket. Categorized as Reserve IP -> Static IP.",
    },
  },
  {
    id: 'tkt-otrs-32484',
    externalId: 'OTRS-2026090422000075',
    ticketNumber: '2026090422000075',
    kriteria: 'Reserve IP',
    subKriteria: 'Reserve IP',
    subject: "Re: Permohonan Reserve IP",
    description: `Re: Permohonan Reserve IP
[Article 72589]: P {margin-top:0;margin-bottom:0;} Dear Rekan, Terkait requestnya sudah selesai di eksekusi, Berikut terlampir MOP dan Juga Reportnya : Demikian Yang Dapat Diinformasikan, Terimakasih dan Best Regards, &nbsp; Mochamad Sonda Nur Pasha &nbsp; From: AZZAHRA NADYA KAHPIASA &lt;azzahra.nadya@bankbsi.co.id&gt; Sent: Friday, September 4, 2026 2:42 PM To: Mochamad Sonda Nur Pasha &lt;mochamad.sonda@lt-integra.com&gt;; Ismail Akbar &lt;ismail.akbar@lt-integra.com&gt;; bsidnsdhcpsupp &lt;bsidnsdhcpsupp@lt-integra.com&gt; Cc: IOG Network &lt;iog_network@bankbsi.co.id&gt; Subject: Fw: Permohonan Reserve IP &nbsp; Dear rekan integra,&nbsp; Tolong di reserved ip berikut Terima kasih Best Regards, Azzahra Nadya Kahpiasa HO &amp; Branch IT Facilities Engineer PT Bank Syariah Indonesia Tbk BSI Tower, Jl. Medan Merdeka Sel. No.17 Lt.18. Jakarta Pusat 10110 From: AGUS RASMAWAN &lt;agus.rasmawan@bankbsi.co.id&gt; Sent: 04 September 2026 11:17 To: IOG Network &lt;iog_network@bankbsi.co.id&gt; Subject: Permohonan Reserve IP &nbsp; Assalamualaikum Wr WB Berikut kami sampaikan permohonan reserve IP untuk kegiatan akreditasi rekanan dengan data sbb : Hostname : PC-PFA-VM IP : 10.2.42.82 Tujuan dari reserve IP agar calon rekanan BSI dapat mendaftarkan secara mandiri melalui PC yang telah disediakan. Wassalamualaikum Wr Wb
[Article 72590]: Hello Customer, We have received your problem report and have created " [Ticket#2026090422000075] Re: Permohonan Reserve IP ". Your Ticket will be answered by a Team Support. Regards, Icare You wrote : Dear Rekan, Terkait requestnya sudah selesai di eksekusi, Berikut terlampir MOP dan Juga Reportnya : [cid:4160f2b8-4478-41a0-b892-12cf9b88a26c] Demikian Yang Dapat Diinformasikan, Terimakasih dan Best Regards, Mochamad So ... [Content truncated for display]`,
    mainCategory: 'Service Request',
    technicalCategory: 'DHCP',
    priority: 'MEDIUM',
    status: 'OPEN',
    requester: 'Bank Syariah Indonesia (BSI)',
    requesterEmail: 'bsi-ops@bankbsi.co.id',
    assigneeId: 'usr-03',
    assigneeName: 'Ismail Ak (ismailak)',
    assignmentGroup: 'OP0899 - BSI DNS & DHCP Infoblox',
    createdAt: '2026-09-07T08:00:00.000Z',
    updatedAt: '2026-09-07T12:00:00.000Z',
    dueAt: '2026-09-08T08:00:00.000Z',
    slaHours: 24,
    slaStatus: 'SAFE',
    ruleEngineSuggested: {
      mainCategory: 'Service Request',
      technicalCategory: 'DHCP',
      priority: 'MEDIUM',
      confidence: 96,
      matchedKeywords: ["reserve ip", "dhcp", "reservation"],
      explanation: "Matched 'Reserve IP / Fixed Address' in ticket. Categorized as Reserve IP -> Reserve IP.",
    },
  },
  {
    id: 'tkt-otrs-32492',
    externalId: 'OTRS-2026090422000155',
    ticketNumber: '2026090422000155',
    kriteria: 'DNS Request',
    subKriteria: 'DNS Record',
    subject: "Permintaan Pembuatan DNS API GW dan DNS Databse untuk Kebutuhan Project Transaksi Digital Luar Negeri (SPP TDLN)",
    description: `Permintaan Pembuatan DNS API GW dan DNS Databse untuk Kebutuhan Project Transaksi Digital Luar Negeri (SPP TDLN)
[Article 72600]: P {margin-top:0;margin-bottom:0;} Assalamu'alaikum, DH Rekan Integra, Terkait adanya project dalam mendukung Pengembangan Sistem untuk Pemungutan Pajak Transaksi Digital Luar Negeri, tolong dapat dibuatkan MOP dari Pembuatan DNS Berikut :&nbsp; Untuk eksekusinya dapat dilakukan pada jum'at , 4 September 2026 Jam 19.30 WIB. sekian dan terima kasih. Wassalam. Best Regards, Ramadhana Fitryanto Core Network, Extranet &amp; Internet Officer M: (+62) 822-7506-4382 E : ramadhana.fitryanto@bankbsi.co.id W: www.bankbsi.co.id PT. Bank Syariah Indonesia, Tbk. | Kantor Pusat Gedung The Tower | Jl. Gatot Subroto No. 27 Kelurahan Karet Semanggi, Kecamatan Setiabudi, Jakarta Selatan, DKI Jakarta 12930 Indonesia
[Article 72601]: Hello Customer, We have received your problem report and have created " [Ticket#2026090422000155] Permintaan Pembuatan DNS API GW dan DNS Databse untuk Kebutuhan Project Transaksi Digital Luar Negeri (SPP TDLN) ". Your Ticket will be answered by a Team Support. Regards, Icare You wrote : Assalamu'alaikum, DH Rekan Integra, Terkait adanya project dalam mendukung Pengembangan Sistem untuk Pemungutan Pajak Transaksi Digital Luar Negeri, tolong dapat dibuatkan MOP dari Pembuatan DNS Berikut : [cid:dae5b029-c29a-4455-b03d-d753db22e898] Untuk eksekusinya dapat dilakukan pada jum'at , 4 September 2026 Jam 19.30 WIB. sekian dan terima kasih. Wassalam. Best Regards, Ramadhana Fitryanto Core Network, Extranet &amp; Internet Officer M: (+62) 822-7506-4382 E :ramadhana.fitryanto@bankbsi.co.id W: www.bankbsi.co.id &lt; http://www.bankbsi.co.id &gt; P.S. : To view the update, please login to Integra Care on&nbsp; https://icare.lt-integra.com/
[Art ... [Content truncated for display]`,
    mainCategory: 'Service Request',
    technicalCategory: 'DNS',
    priority: 'MEDIUM',
    status: 'OPEN',
    requester: 'Bank Syariah Indonesia (BSI)',
    requesterEmail: 'bsi-ops@bankbsi.co.id',
    assigneeId: 'usr-03',
    assigneeName: 'Ismail Ak (ismailak)',
    assignmentGroup: 'OP0899 - BSI DNS & DHCP Infoblox',
    createdAt: '2026-09-07T08:00:00.000Z',
    updatedAt: '2026-09-07T12:00:00.000Z',
    dueAt: '2026-09-08T08:00:00.000Z',
    slaHours: 24,
    slaStatus: 'SAFE',
    ruleEngineSuggested: {
      mainCategory: 'Service Request',
      technicalCategory: 'DNS',
      priority: 'MEDIUM',
      confidence: 96,
      matchedKeywords: ["dns", "dns record", "infoblox"],
      explanation: "Matched 'Penambahan DNS' request. Categorized as DNS Request -> Sub-kriteria: DNS Record.",
    },
  },
  {
    id: 'tkt-otrs-32533',
    externalId: 'OTRS-2026090722000015',
    ticketNumber: '2026090722000015',
    kriteria: 'DNS Request',
    subKriteria: 'DNS Record',
    subject: "Fw: [PERMOHONAN REQUEST DNS APP & WEB MIGRASI SORT TO DCI]",
    description: `Fw: [PERMOHONAN REQUEST DNS APP & WEB MIGRASI SORT TO DCI]
[Article 72667]: P {margin-top:0;margin-bottom:0;} Dear rekan integra Tolong dibuatkan MOP terkait request dns berikut Terima kasih Best Regards Evelio Excellenta From: MUHAMMAD ZAKY RAFFINALDY &lt;m.zaky@bankbsi.co.id&gt; Sent: Friday, September 4, 2026 5:20 PM To: IOG CR Network &lt;iog_crnetwork@bankbsi.co.id&gt;; IOG Officer On Duty &lt;iog_monitoring@bankbsi.co.id&gt; Cc: DEWI AYUNAH &lt;dewi.ayunah@bankbsi.co.id&gt;; Muhammad Faiq Ardyanto Putro &lt;muhammad.putro@bankbsi.co.id&gt;; ANDHINI WIDYASARI PUTRI &lt;andhini.widyasari@bankbsi.co.id&gt;; Dila Kiranti &lt;dila.kiranti@bankbsi.co.id&gt;; Azka Lazuardi Farghani &lt;azka.lazuardi@bankbsi.co.id&gt;; HARIS KURNIAWAN &lt;haris.kurniawan@bankbsi.co.id&gt; Subject: [PERMOHONAN REQUEST DNS APP &amp; WEB MIGRASI SORT TO DCI] &nbsp; Dear Tim Network - IOG Sehubungan akan dilaksanakan kembali DRP dan Migrasi DCl di tahun 2026, mohon bantuannya untuk dilakukan percepatan aktivitas berikut pada Aplikasi SORT 1. Request DNS APP SORT 2. Request DNS WEB SORT Izin berikut kami lampirkan juga memo yang masih sirkulir Group Head ASP dan FKK yang dibutuhkan. Terima kasih. Wassalamualaikum wr wb. Regards, Muhammad Zaky Raffinaldy IT ASP
[Article 72668]: Hello Customer, We have received your problem report and have created " [Ticket#2026090722000015] Fw: [PERMOHONAN REQUEST DNS APP &amp; WEB MIGRASI SORT TO DCI] ". Your Ticket will be answered by a Team Support. Regards, Icare You wrote : Dear rekan integra Tolong dibuatkan MOP terkait request dns berikut Terima kasih Best Regards Evelio Excellenta ________________________________ From: MUHAMMAD ZAKY RAFFINALDY &lt;m.zaky@bankbsi.co.id&gt; Sent: Friday, September 4, 2026 5:20 PM To: IOG CR Network &lt;iog_crnetwork@bankb ... [Content truncated for display]`,
    mainCategory: 'Service Request',
    technicalCategory: 'DNS',
    priority: 'MEDIUM',
    status: 'OPEN',
    requester: 'Bank Syariah Indonesia (BSI)',
    requesterEmail: 'bsi-ops@bankbsi.co.id',
    assigneeId: 'usr-03',
    assigneeName: 'Ismail Ak (ismailak)',
    assignmentGroup: 'OP0899 - BSI DNS & DHCP Infoblox',
    createdAt: '2026-09-07T08:00:00.000Z',
    updatedAt: '2026-09-07T12:00:00.000Z',
    dueAt: '2026-09-08T08:00:00.000Z',
    slaHours: 24,
    slaStatus: 'SAFE',
    ruleEngineSuggested: {
      mainCategory: 'Service Request',
      technicalCategory: 'DNS',
      priority: 'MEDIUM',
      confidence: 96,
      matchedKeywords: ["dns", "dns record", "infoblox"],
      explanation: "Matched 'Penambahan DNS' request. Categorized as DNS Request -> Sub-kriteria: DNS Record.",
    },
  },
  {
    id: 'tkt-otrs-32535',
    externalId: 'OTRS-2026090722000033',
    ticketNumber: '2026090722000033',
    kriteria: 'DNS Request',
    subKriteria: 'A Record',
    subject: "Fw: Permohonan pembuatan DNS pada server DB ATM Monitoring untuk kebutuhan DRC",
    description: `Fw: Permohonan pembuatan DNS pada server DB ATM Monitoring untuk kebutuhan DRC
[Article 72672]: P {margin-top:0;margin-bottom:0;} Dear pak hendik Berikut terlampir dokumen Mop&nbsp; mohon reviewnya dan perbaikannya jika ada kekurangan serta kesalahan kata Terima kasih B/R From: LAIL NUGRAHA PRATAMA &lt;lail.nugraha@bankbsi.co.id&gt; Sent: Monday, September 7, 2026 11:06 To: Ismail Akbar &lt;ismail.akbar@lt-integra.com&gt;; Mochamad Sonda Nur Pasha &lt;mochamad.sonda@lt-integra.com&gt;; Hendik Rubin Yulianto &lt;hendik@lt-integra.com&gt;; Manzila Izniardi Djomiy &lt;djomiy@lt-integra.com&gt; Cc: IOG Network &lt;iog_network@bankbsi.co.id&gt; Subject: Fw: Permohonan pembuatan DNS pada server DB ATM Monitoring untuk kebutuhan DRC &nbsp; Dear Rekan Integra, Mohon disiapkan MOP terkait penambahan A Record berikut :&nbsp; db-atmon.bankbsi.co.id = 10.216.6.133 dev-db-atmon.bankbsi.co.id =10.0.118.30 Terima kasih Best Regards, Lail Nugraha Pratama Core Network, Extranet &amp; Internet Officer &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; M: (+62) 8558899000 E : lail.nugraha@bankbsi.co.id W: www.bankbsi.co.id PT. Bank Syariah Indonesia, Tbk.&nbsp;| Kantor Pusat Gedung The Tower&nbsp;| Jl. Gatot Subroto No. 27 Kelurahan Karet Semanggi, Kecamatan Setiabudi, Jakarta Selatan, DKI Jakarta 12930 Indonesia From: Ayasha Naila Ismunandar &lt;ayasha.naila@bankbsi.co.id&gt; Sent: Monday, September 7, 2026 10:48 AM To: Ibnu adi sukoco720 &lt;ibnu.sukoco720@bankbsi.co.id&gt;; IOG CR Network &lt;iog_crnetwork@bankbsi.co.id&gt; Cc: IOG Network &lt;iog_network@bankbsi.co.id&gt;; IRWAN YACOB &lt;irwan.yacob@bankbsi.co.id&gt;; MUHAMMAD REZA HARDIANSYAH &lt;m.hardiansyah@bankbsi.co.id&gt;; PAWIT SINGGIH HARYADI &lt;pawit.singgih@bankbsi.co.id&gt;; RAFIATI &lt;rafiati@bankbsi.co.id&gt; Subject: Re: Permohonan  ... [Content truncated for display]`,
    mainCategory: 'Service Request',
    technicalCategory: 'DNS',
    priority: 'MEDIUM',
    status: 'OPEN',
    requester: 'Bank Syariah Indonesia (BSI)',
    requesterEmail: 'bsi-ops@bankbsi.co.id',
    assigneeId: 'usr-03',
    assigneeName: 'Ismail Ak (ismailak)',
    assignmentGroup: 'OP0899 - BSI DNS & DHCP Infoblox',
    createdAt: '2026-09-07T08:00:00.000Z',
    updatedAt: '2026-09-07T12:00:00.000Z',
    dueAt: '2026-09-08T08:00:00.000Z',
    slaHours: 24,
    slaStatus: 'SAFE',
    ruleEngineSuggested: {
      mainCategory: 'Service Request',
      technicalCategory: 'DNS',
      priority: 'MEDIUM',
      confidence: 96,
      matchedKeywords: ["dns", "a record", "infoblox"],
      explanation: "Matched 'Penambahan DNS' request. Categorized as DNS Request -> Sub-kriteria: A Record.",
    },
  },
  {
    id: 'tkt-otrs-32537',
    externalId: 'OTRS-2026090722000051',
    ticketNumber: '2026090722000051',
    kriteria: 'IPAM',
    subKriteria: 'IPAM Allocation',
    subject: "Fw: Permohonan IP Address dan Server Development untuk Aplikasi Billing Tools Hasanah Card INP-1759",
    description: `Fw: Permohonan IP Address dan Server Development untuk Aplikasi Billing Tools Hasanah Card INP-1759
[Article 72680]: P {margin-top:0;margin-bottom:0;} Untuk melindungi privasi Anda, konten jauh diblokir. Beban diblokir konten. Dear rekan integra, Tolong add IPAM Terima kasih Best Regards Salman Alfarisy From: Salman Alfarisy &lt;salman.alfarisy@bankbsi.co.id&gt; Sent: 26 August 2026 11:42 To: ABRAR RAVIDHIA &lt;abrar.ravidhia@bankbsi.co.id&gt;; Farah Husna Nabilah &lt;farah.husna0210@bankbsi.co.id&gt;; IOG Network &lt;iog_network@bankbsi.co.id&gt; Cc: Linda Khoerunisa &lt;linda.khoerunisa@bankbsi.co.id&gt;; Syifa nur khoiriyah &lt;nur.khoiriyah@bankbsi.co.id&gt;; MUHAMMAD HAMDAN &lt;muhammad.hamdan@bankbsi.co.id&gt;; NUR SHOBI MABRUR &lt;nur.shobi@bankbsi.co.id&gt; Subject: Re: Permohonan IP Address dan Server Development untuk Aplikasi Billing Tools Hasanah Card INP-1759 &nbsp; Dear @ABRAR RAVIDHIA Berikut alokasi 1 IP FE dan 5 IP BE Dev Isolated untuk Aplikasi Billing Tools Hasanah terlampir dalam sheet berikut. Mohon dapat diperiksa kembali. ​ ​ IP Address Request Form - Farah HN IDG 240826 - Aplikasi Billing Tools Hasanah Card.xlsx ​ ​ IP Address Request Form Nama Requestor M Fadhil F M Fadhil F M Fadhil F M Fadhil F M Fadhil F M Fadhil F NIP 2502022071 2502022071 2502022071 2502022071 2502022071 2502022071 Jabatan Junior Software Engineer Junior Software Engineer Junior Software Engineer Junior Software Engineer Junior Software Engineer Junior Software Engineer Department Operations &amp; Internal Application System Development Operations &amp; Internal Application System Development Operations &amp; Internal Application System Development Operations &amp; Internal Application System Development Operations &amp; Internal Application System Development Operations &a ... [Content truncated for display]`,
    mainCategory: 'Service Request',
    technicalCategory: 'Infrastructure',
    priority: 'MEDIUM',
    status: 'OPEN',
    requester: 'Bank Syariah Indonesia (BSI)',
    requesterEmail: 'bsi-ops@bankbsi.co.id',
    assigneeId: 'usr-03',
    assigneeName: 'Ismail Ak (ismailak)',
    assignmentGroup: 'OP0899 - BSI DNS & DHCP Infoblox',
    createdAt: '2026-09-07T08:00:00.000Z',
    updatedAt: '2026-09-07T12:00:00.000Z',
    dueAt: '2026-09-08T08:00:00.000Z',
    slaHours: 24,
    slaStatus: 'SAFE',
    ruleEngineSuggested: {
      mainCategory: 'Service Request',
      technicalCategory: 'Infrastructure',
      priority: 'MEDIUM',
      confidence: 96,
      matchedKeywords: ["ipam", "alokasi ip", "isolated dev"],
      explanation: "Matched 'IPAM' keyword in ticket request. Categorized as IPAM -> IPAM Allocation.",
    },
  },
  {
    id: 'tkt-otrs-32538',
    externalId: 'OTRS-2026090722000061',
    ticketNumber: '2026090722000061',
    kriteria: 'IPAM',
    subKriteria: 'IPAM & PTR Allocation',
    subject: "Fw: Request IP Server dan Server PTR Medallion",
    description: `Fw: Request IP Server dan Server PTR Medallion
[Article 72684]: P {margin-top:0;margin-bottom:0;} Untuk melindungi privasi Anda, konten jauh diblokir. Beban diblokir konten. Dear rekan integra, Tolong add IPAM Terima kasih Best Regards Salman Alfarisy From: Salman Alfarisy &lt;salman.alfarisy@bankbsi.co.id&gt; Sent: 27 August 2026 14:23 To: ABRAR RAVIDHIA &lt;abrar.ravidhia@bankbsi.co.id&gt;; Reza Firdaus &lt;ven.firdaus@bankbsi.co.id&gt;; IOG Network &lt;iog_network@bankbsi.co.id&gt; Cc: RICKY MAHENDRA &lt;ricky.mahendra@bankbsi.co.id&gt;; SUMINI WIJI LESTARI &lt;sumini.wiji@bankbsi.co.id&gt;; Linda Khoerunisa &lt;linda.khoerunisa@bankbsi.co.id&gt;; Syifa nur khoiriyah &lt;nur.khoiriyah@bankbsi.co.id&gt; Subject: Re: Request IP Server dan Server PTR Medallion &nbsp; Dear @ABRAR RAVIDHIA Berikut alokasi 1 IP FE dan 4 IP BE DCI untuk Medallion terlampir dalam sheet berikut. Mohon dapat diperiksa kembali. ​ ​ IP Address Request Form - Reza F IDG 270826 - RBS PTR.xlsx ​ ​ IP Address Request Form Nama Requestor Sumini Wiji Lestari Sumini Wiji Lestari Sumini Wiji Lestari Sumini Wiji Lestari Sumini Wiji Lestari NIP 2194013096 2194013096 2194013096 2194013096 2194013096 Jabatan Senior Software Engineer Senior Software Engineer Senior Software Engineer Senior Software Engineer Senior Software Engineer Department Operations &amp; Internal Application System Development Operations &amp; Internal Application System Development Operations &amp; Internal Application System Development Operations &amp; Internal Application System Development Operations &amp; Internal Application System Development Environment IP Production Production Production Production Production Fungsi Penggunaan IP PTR PTR PTR PTR PTR Nama Aplikasi/ Platform Medallion Medallion Medallion Medallion Medallion Untu ... [Content truncated for display]`,
    mainCategory: 'Service Request',
    technicalCategory: 'Infrastructure',
    priority: 'MEDIUM',
    status: 'OPEN',
    requester: 'Bank Syariah Indonesia (BSI)',
    requesterEmail: 'bsi-ops@bankbsi.co.id',
    assigneeId: 'usr-03',
    assigneeName: 'Ismail Ak (ismailak)',
    assignmentGroup: 'OP0899 - BSI DNS & DHCP Infoblox',
    createdAt: '2026-09-07T08:00:00.000Z',
    updatedAt: '2026-09-07T12:00:00.000Z',
    dueAt: '2026-09-08T08:00:00.000Z',
    slaHours: 24,
    slaStatus: 'SAFE',
    ruleEngineSuggested: {
      mainCategory: 'Service Request',
      technicalCategory: 'Infrastructure',
      priority: 'MEDIUM',
      confidence: 96,
      matchedKeywords: ["ipam", "alokasi ip", "isolated dev"],
      explanation: "Matched 'IPAM' keyword in ticket request. Categorized as IPAM -> IPAM & PTR Allocation.",
    },
  },
  {
    id: 'tkt-otrs-32540',
    externalId: 'OTRS-2026090722000088',
    ticketNumber: '2026090722000088',
    kriteria: 'DNS Request',
    subKriteria: 'A Record',
    subject: "Fw: Permohonan Pemasangan DNS pada Environment Production DONAT DCI",
    description: `Fw: Permohonan Pemasangan DNS pada Environment Production DONAT DCI
[Article 72687]: P {margin-top:0;margin-bottom:0;} Dear rekan integra Tolong dibuatkan MOP berikut Terima kasih Best Regards Evelio Excellenta From: CAHYO ADHI HARTANTO &lt;cahyo.hartanto@bankbsi.co.id&gt; Sent: Wednesday, August 19, 2026 3:08 PM To: IOG CR Network &lt;iog_crnetwork@bankbsi.co.id&gt; Cc: IOG Network &lt;iog_network@bankbsi.co.id&gt;; WINDIKURNIA APRIYANTO &lt;windikurnia.a@bankbsi.co.id&gt;; YUDHA AGUNG ALAMSYAH &lt;yudha.agung@bankbsi.co.id&gt;; GANI UTOMO &lt;gani.utomo@bankbsi.co.id&gt;; Dwi Andre Vebriansyah &lt;andre.vebriansyah@bankbsi.co.id&gt; Subject: Permohonan Pemasangan DNS pada Environment Production DONAT DCI &nbsp; Assalamualaikum rekan-rekan IOG Change Request&nbsp;dan IOG Network Berkaitan dengan persiapan implementasi aplikasi DMS(Document Management System) Internal DONAT (Document Organization Navigation Archiving Tools) pada environment Production, maka diperlukan pemasangan DNS pada masing-masing IP LB, Server dan Net App Storage DCI agar aplikasi dapat diakses melalui DNS. IP LB Customer :&nbsp; 10.222.8.134 (donatcf.bankbsi.co.id) IP LB Non Customer 10.222.8.135 (donatncf.bankbsi.co.id) IP Server App 1 Customer 10.216.20.176&nbsp; (donatapp1cf.bankbsi.co.id) IP Server App 2 Customer 10.216.20.177&nbsp; (donatapp2cf.bankbsi.co.id) IP Server App 1 Non Customer 10.216.20.178 (donatapp1ncf.bankbsi.co.id) IP Server App 2 Non Customer 10.216.20.179&nbsp; (donatapp2ncf.bankbsi.co.id) IP Server App Scheduler 10.216.20.180 (donatappscheduler.bankbsi.co.id) IP Server DB 10.216.20.181 (donatdb.bankbsi.co.id) IP Server DB Mirroring 10.216.20.182 (donatdbmirroring.bankbsi.co.id) IP Net App Storage 10.216.20.183 (donatstorage.bankbsi.co.id) Terkait hal tersebut, kami mengajuka ... [Content truncated for display]`,
    mainCategory: 'Service Request',
    technicalCategory: 'DNS',
    priority: 'MEDIUM',
    status: 'OPEN',
    requester: 'Bank Syariah Indonesia (BSI)',
    requesterEmail: 'bsi-ops@bankbsi.co.id',
    assigneeId: 'usr-03',
    assigneeName: 'Ismail Ak (ismailak)',
    assignmentGroup: 'OP0899 - BSI DNS & DHCP Infoblox',
    createdAt: '2026-09-07T08:00:00.000Z',
    updatedAt: '2026-09-07T12:00:00.000Z',
    dueAt: '2026-09-08T08:00:00.000Z',
    slaHours: 24,
    slaStatus: 'SAFE',
    ruleEngineSuggested: {
      mainCategory: 'Service Request',
      technicalCategory: 'DNS',
      priority: 'MEDIUM',
      confidence: 96,
      matchedKeywords: ["dns", "a record", "infoblox"],
      explanation: "Matched 'Penambahan DNS' request. Categorized as DNS Request -> Sub-kriteria: A Record.",
    },
  },
  {
    id: 'tkt-otrs-32541',
    externalId: 'OTRS-2026090722000097',
    ticketNumber: '2026090722000097',
    kriteria: 'DNS Request',
    subKriteria: 'CNAME',
    subject: "Fw: Permohonan Request CNAME bridgecon.bankbsi.co.id",
    description: `Fw: Permohonan Request CNAME bridgecon.bankbsi.co.id
[Article 72691]: P {margin-top:0;margin-bottom:0;} Dear rekan integra Tolong dibuatkan MOP terkait request berikut Terima kasih Best Regards Evelio Excellenta From: Aldra Kasyfil Aziz &lt;aldra.kasyfil@bankbsi.co.id&gt; Sent: Friday, August 21, 2026 3:02 PM To: IOG CR Network &lt;iog_crnetwork@bankbsi.co.id&gt;; RAFIATI &lt;rafiati@bankbsi.co.id&gt;; PAWIT SINGGIH HARYADI &lt;pawit.singgih@bankbsi.co.id&gt; Cc: SULISTIANTO &lt;sulistianto@bankbsi.co.id&gt;; RAHMAWAN ILHAM ALFATH &lt;rahmawan.ilham@bankbsi.co.id&gt;; Farhan Ardhana &lt;farhan.ardhana@bankbsi.co.id&gt;; Syifa nur khoiriyah &lt;nur.khoiriyah@bankbsi.co.id&gt;; Linda Khoerunisa &lt;linda.khoerunisa@bankbsi.co.id&gt; Subject: Permohonan Request CNAME bridgecon.bankbsi.co.id &nbsp; Dear Team CR Network yang berbahagia, Assalamualaikum warahmatullahi wabarakatuh, Mohon bantuannya untuk melakukan penambahan alias baru: bridgecon.bankbsi.co.id, target IP Proxy 10.0.96.121 Untuk lebih detail, saya lampirkan file FKK berikut dengan SS E-Doc, terima kasih. Wassalamualaikum warahmatullahi wabarakatuh. Regards, Aldra Kasyfil Aziz
[Article 72692]: Hello Customer, We have received your problem report and have created " [Ticket#2026090722000097] Fw: Permohonan Request CNAME bridgecon.bankbsi.co.id ". Your Ticket will be answered by a Team Support. Regards, Icare You wrote : Dear rekan integra Tolong dibuatkan MOP terkait request berikut Terima kasih Best Regards Evelio Excellenta ________________________________ From: Aldra Kasyfil Aziz &lt;aldra.kasyfil@bankbsi.co.id&gt; Sent: Friday, August 21, 2026 3:02 PM To: IOG CR Network &lt;iog_crnetwork@bankbsi.co.id&gt;; RAFIATI &lt;rafiati@bankbsi.co.id&gt;; PAWIT SINGGIH HARYADI &lt;pawit.singgih@bankbsi.co.id&gt; Cc: SULI ... [Content truncated for display]`,
    mainCategory: 'Service Request',
    technicalCategory: 'DNS',
    priority: 'MEDIUM',
    status: 'OPEN',
    requester: 'Bank Syariah Indonesia (BSI)',
    requesterEmail: 'bsi-ops@bankbsi.co.id',
    assigneeId: 'usr-03',
    assigneeName: 'Ismail Ak (ismailak)',
    assignmentGroup: 'OP0899 - BSI DNS & DHCP Infoblox',
    createdAt: '2026-09-07T08:00:00.000Z',
    updatedAt: '2026-09-07T12:00:00.000Z',
    dueAt: '2026-09-08T08:00:00.000Z',
    slaHours: 24,
    slaStatus: 'SAFE',
    ruleEngineSuggested: {
      mainCategory: 'Service Request',
      technicalCategory: 'DNS',
      priority: 'MEDIUM',
      confidence: 96,
      matchedKeywords: ["dns", "cname", "infoblox"],
      explanation: "Matched 'Penambahan DNS' request. Categorized as DNS Request -> Sub-kriteria: CNAME.",
    },
  },
  {
    id: 'tkt-otrs-32552',
    externalId: 'OTRS-2026090722000202',
    ticketNumber: '2026090722000202',
    kriteria: 'DNS Request',
    subKriteria: 'A Record',
    subject: "Fw: [MIGRASI DCI - SORT] Permohonan Request DNS Database SORT",
    description: `Fw: [MIGRASI DCI - SORT] Permohonan Request DNS Database SORT
[Article 72713]: P {margin-top:0;margin-bottom:0;} Dear rekan integra Tolong buatkan MOP untuk request berikut&nbsp; Terima kasih Best Regards Evelio Excellenta From: MUHAMMAD ZAKY RAFFINALDY &lt;m.zaky@bankbsi.co.id&gt; Sent: Thursday, September 3, 2026 2:45 PM To: IOG CR Network &lt;iog_crnetwork@bankbsi.co.id&gt;; IOG Officer On Duty &lt;iog_monitoring@bankbsi.co.id&gt; Cc: FITRIANTI KAUTSAR &lt;fitrianti.kautsar@bankbsi.co.id&gt;; DEWI AYUNAH &lt;dewi.ayunah@bankbsi.co.id&gt;; SUHENDRA WINATA &lt;suhendra.winata@bankbsi.co.id&gt;; Muhammad Faiq Ardyanto Putro &lt;muhammad.putro@bankbsi.co.id&gt;; Azka Lazuardi Farghani &lt;azka.lazuardi@bankbsi.co.id&gt;; HARIS KURNIAWAN &lt;haris.kurniawan@bankbsi.co.id&gt; Subject: [MIGRASI DCI - SORT] Permohonan Request DNS Database SORT &nbsp; Dear Tim Network - IOG Sehubungan akan dilaksanakan kembali DRP dan Migrasi DCl di tahun 2026, mohon bantuannya untuk dilakukan percepatan aktivitas berikut pada Aplikasi SORT 1. Request DNS DB SORT Izin berikut kami lampirkan juga memo yang masih sirkulir Group Head ASP dan FKK yang dibutuhkan. Terima kasih. Wassalamualaikum wr wb. Regards, Muhammad Zaky Raffinaldy IT ASP
[Article 72714]: Hello Customer, We have received your problem report and have created " [Ticket#2026090722000202] Fw: [MIGRASI DCI - SORT] Permohonan Request DNS Database SORT ". Your Ticket will be answered by a Team Support. Regards, Icare You wrote : Dear rekan integra Tolong buatkan MOP untuk request berikut Terima kasih Best Regards Evelio Excellenta ________________________________ From: MUHAMMAD ZAKY RAFFINALDY &lt;m.zaky@bankbsi.co.id&gt; Sent: Thursday, September 3, 2026 2:45 PM To: IOG CR Network &lt;iog_crnetwork@bankbsi.co.id&gt;; IOG Officer On D ... [Content truncated for display]`,
    mainCategory: 'Service Request',
    technicalCategory: 'DNS',
    priority: 'MEDIUM',
    status: 'OPEN',
    requester: 'Bank Syariah Indonesia (BSI)',
    requesterEmail: 'bsi-ops@bankbsi.co.id',
    assigneeId: 'usr-03',
    assigneeName: 'Ismail Ak (ismailak)',
    assignmentGroup: 'OP0899 - BSI DNS & DHCP Infoblox',
    createdAt: '2026-09-07T08:00:00.000Z',
    updatedAt: '2026-09-07T12:00:00.000Z',
    dueAt: '2026-09-08T08:00:00.000Z',
    slaHours: 24,
    slaStatus: 'SAFE',
    ruleEngineSuggested: {
      mainCategory: 'Service Request',
      technicalCategory: 'DNS',
      priority: 'MEDIUM',
      confidence: 96,
      matchedKeywords: ["dns", "a record", "infoblox"],
      explanation: "Matched 'Penambahan DNS' request. Categorized as DNS Request -> Sub-kriteria: A Record.",
    },
  },
  {
    id: 'tkt-otrs-32559',
    externalId: 'OTRS-2026090722000275',
    ticketNumber: '2026090722000275',
    kriteria: 'DNS Request',
    subKriteria: 'A Record',
    subject: "Re: Permohonan pembuatan DNS pada server DB ATM Monitoring untuk kebutuhan DRC",
    description: `Re: Permohonan pembuatan DNS pada server DB ATM Monitoring untuk kebutuhan DRC
[Article 72733]: P {margin-top:0;margin-bottom:0;} Dear Rekan, Terkait requestnya sudah selesai di eksekusi, Berikut terlampir MOP dan Juga Reportnya : Demikian Yang Dapat Diinformasikan, Terimakasih dan Best Regards, &nbsp; Mochamad Sonda Nur Pasha &nbsp; From: LAIL NUGRAHA PRATAMA &lt;lail.nugraha@bankbsi.co.id&gt; Sent: Monday, September 7, 2026 11:06 AM To: Ismail Akbar &lt;ismail.akbar@lt-integra.com&gt;; Mochamad Sonda Nur Pasha &lt;mochamad.sonda@lt-integra.com&gt;; Hendik Rubin Yulianto &lt;hendik@lt-integra.com&gt;; Manzila Izniardi Djomiy &lt;djomiy@lt-integra.com&gt; Cc: IOG Network &lt;iog_network@bankbsi.co.id&gt; Subject: Fw: Permohonan pembuatan DNS pada server DB ATM Monitoring untuk kebutuhan DRC &nbsp; Dear Rekan Integra, Mohon disiapkan MOP terkait penambahan A Record berikut :&nbsp; db-atmon.bankbsi.co.id = 10.216.6.133 dev-db-atmon.bankbsi.co.id =10.0.118.30 Terima kasih Best Regards, Lail Nugraha Pratama Core Network, Extranet &amp; Internet Officer &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; M: (+62) 8558899000 E : lail.nugraha@bankbsi.co.id W: www.bankbsi.co.id PT. Bank Syariah Indonesia, Tbk.&nbsp;| Kantor Pusat Gedung The Tower&nbsp;| Jl. Gatot Subroto No. 27 Kelurahan Karet Semanggi, Kecamatan Setiabudi, Jakarta Selatan, DKI Jakarta 12930 Indonesia From: Ayasha Naila Ismunandar &lt;ayasha.naila@bankbsi.co.id&gt; Sent: Monday, September 7, 2026 10:48 AM To: Ibnu adi sukoco720 &lt;ibnu.sukoco720@bankbsi.co.id&gt;; IOG CR Network &lt;iog_crnetwork@bankbsi.co.id&gt; Cc: IOG Network &lt;iog_network@bankbsi.co.id&gt;; IRWAN YACOB &lt;irwan.yacob@bankbsi.co.id&gt;; MUHAMMAD REZA HARDIANSYAH &lt;m.hardiansyah@bankbsi.co.id&gt;; PAWIT SINGGIH HARYADI &lt;pawit.singgih@bankbsi.co.id&g ... [Content truncated for display]`,
    mainCategory: 'Service Request',
    technicalCategory: 'DNS',
    priority: 'MEDIUM',
    status: 'OPEN',
    requester: 'Bank Syariah Indonesia (BSI)',
    requesterEmail: 'bsi-ops@bankbsi.co.id',
    assigneeId: 'usr-03',
    assigneeName: 'Ismail Ak (ismailak)',
    assignmentGroup: 'OP0899 - BSI DNS & DHCP Infoblox',
    createdAt: '2026-09-07T08:00:00.000Z',
    updatedAt: '2026-09-07T12:00:00.000Z',
    dueAt: '2026-09-08T08:00:00.000Z',
    slaHours: 24,
    slaStatus: 'SAFE',
    ruleEngineSuggested: {
      mainCategory: 'Service Request',
      technicalCategory: 'DNS',
      priority: 'MEDIUM',
      confidence: 96,
      matchedKeywords: ["dns", "a record", "infoblox"],
      explanation: "Matched 'Penambahan DNS' request. Categorized as DNS Request -> Sub-kriteria: A Record.",
    },
  },
  {
    id: 'tkt-otrs-32560',
    externalId: 'OTRS-2026090722000284',
    ticketNumber: '2026090722000284',
    kriteria: 'DNS Request',
    subKriteria: 'A Record',
    subject: "Fw: [Migrasi DCI - Sistem Informasi Kepatuhan] Permohonan Request DNS Database Sistem Informasi Kepatuhan",
    description: `Fw: [Migrasi DCI - Sistem Informasi Kepatuhan] Permohonan Request DNS Database Sistem Informasi Kepatuhan
[Article 72735]: P {margin-top:0;margin-bottom:0;} Untuk melindungi privasi Anda, konten jauh diblokir. Beban diblokir konten. Dear rekan integra Tolong dibuatkan MOP terkait request berikut&nbsp; Arecord : sik.bankbsi.co.id IP : 10.216.245.40 (Disabled) Arecord : sikdb.bankbsi.co.id IP : 10.216.245.45 (Enabled) IP : 10.0.32.104 (Disabled) Terima kasih Best Regards Evelio Excellenta From: Puti Andini &lt;ven.andini@bankbsi.co.id&gt; Sent: Friday, September 4, 2026 1:46 PM To: IOG CR Network &lt;iog_crnetwork@bankbsi.co.id&gt; Cc: DEWI AYUNAH &lt;dewi.ayunah@bankbsi.co.id&gt;; Dila Kiranti &lt;dila.kiranti@bankbsi.co.id&gt;; MUHAMMAD ZAKY RAFFINALDY &lt;m.zaky@bankbsi.co.id&gt;; FARALITA FAISAL &lt;faralita.faisal@bankbsi.co.id&gt;; Azka Lazuardi Farghani &lt;azka.lazuardi@bankbsi.co.id&gt;; HARIS KURNIAWAN &lt;haris.kurniawan@bankbsi.co.id&gt;; Ayasha Naila Ismunandar &lt;ayasha.naila@bankbsi.co.id&gt;; FITRIANTI KAUTSAR &lt;fitrianti.kautsar@bankbsi.co.id&gt;; FAJAR IRIANTO PRAJOKO &lt;fajar.irianto@bankbsi.co.id&gt;; SUHENDRA WINATA &lt;suhendra.winata@bankbsi.co.id&gt;; Syifa Lutfiah &lt;ven.lutfiah@bankbsi.co.id&gt; Subject: Re: [Migrasi DCI - Sistem Informasi Kepatuhan] Permohonan Request DNS Database Sistem Informasi Kepatuhan &nbsp; Dear Tim Network - IOG Sehubungan akan dilaksanakan kembali DRP dan Migrasi DCI di tahun 2026, mohon bantuannya untuk dilakukan percepatan aktivitas berikut pada Aplikasi Sistem Informasi Kepatuhan :&nbsp; Request Update Naming DNS web Sistem Informasi Kepatuhan (sik.bankbsi.co.id) di DCI Izin berikut kami lampirkan juga memo dan form yang dibutuhkan. ​ ​ FKK Request Update DNS Web SIK.pdf ​ ​ Best Regards, Puti Andini IT ASP From ... [Content truncated for display]`,
    mainCategory: 'Service Request',
    technicalCategory: 'DNS',
    priority: 'MEDIUM',
    status: 'OPEN',
    requester: 'Bank Syariah Indonesia (BSI)',
    requesterEmail: 'bsi-ops@bankbsi.co.id',
    assigneeId: 'usr-03',
    assigneeName: 'Ismail Ak (ismailak)',
    assignmentGroup: 'OP0899 - BSI DNS & DHCP Infoblox',
    createdAt: '2026-09-07T08:00:00.000Z',
    updatedAt: '2026-09-07T12:00:00.000Z',
    dueAt: '2026-09-08T08:00:00.000Z',
    slaHours: 24,
    slaStatus: 'SAFE',
    ruleEngineSuggested: {
      mainCategory: 'Service Request',
      technicalCategory: 'DNS',
      priority: 'MEDIUM',
      confidence: 96,
      matchedKeywords: ["dns", "a record", "infoblox"],
      explanation: "Matched 'Penambahan DNS' request. Categorized as DNS Request -> Sub-kriteria: A Record.",
    },
  },
  {
    id: 'tkt-otrs-32561',
    externalId: 'OTRS-2026090722000293',
    ticketNumber: '2026090722000293',
    kriteria: 'DNS Request',
    subKriteria: 'A Record',
    subject: "Fw: [Migrasi DCI - CMON] Perubahan Naming DNS APP C-Mon untuk IP DCI",
    description: `Fw: [Migrasi DCI - CMON] Perubahan Naming DNS APP C-Mon untuk IP DCI
[Article 72739]: P {margin-top:0;margin-bottom:0;} Dear rekan integra Tolong dibuatkan MOP terkait request dns berikut&nbsp; DNS c-mon.bankbsi.co.id IP Address 10.216.249.21 (disabled) Terima kasih Best Regards Evelio Excellenta From: Dila Kiranti &lt;dila.kiranti@bankbsi.co.id&gt; Sent: Thursday, September 3, 2026 3:16 PM To: IOG CR Network &lt;iog_crnetwork@bankbsi.co.id&gt; Cc: IOG Network &lt;iog_network@bankbsi.co.id&gt;; DEWI AYUNAH &lt;dewi.ayunah@bankbsi.co.id&gt;; YAN ACHSRI &lt;yan.achsri@bankbsi.co.id&gt;; RIZKI ADRIAN 02 &lt;rizki.adrian02@bankbsi.co.id&gt;; Azka Lazuardi Farghani &lt;azka.lazuardi@bankbsi.co.id&gt;; HARIS KURNIAWAN &lt;haris.kurniawan@bankbsi.co.id&gt;; FITRIANTI KAUTSAR &lt;fitrianti.kautsar@bankbsi.co.id&gt;; SUHENDRA WINATA &lt;suhendra.winata@bankbsi.co.id&gt;; FARALITA FAISAL &lt;faralita.faisal@bankbsi.co.id&gt; Subject: [Migrasi DCI - CMON] Perubahan Naming DNS APP C-Mon untuk IP DCI &nbsp; Selamat Pagi rekan-rekan IOG. Sehubungan akan dilaksanakan kembali DRP dan Migrasi DCI di tahun 2026, mohon bantuannya untuk dilakukan percepatan aktivitas berikut pada Aplikasi C-Mon yang akan dilaksanakan hari Selasa, 8 September 2026. Perubahan Naming DNS APP C-Mon untuk IP DCI Izin berikut kami lampirkan juga memo dan form yang dibutuhkan. Terima kasih. Wassalamualaikum wr wb. Regards, Dila Kiranti Release Management Officer | ASP
[Article 72740]: Hello Customer, We have received your problem report and have created " [Ticket#2026090722000293] Fw: [Migrasi DCI - CMON] Perubahan Naming DNS APP C-Mon untuk IP DCI ". Your Ticket will be answered by a Team Support. Regards, Icare You wrote : Dear rekan integra Tolong dibuatkan MOP terkait request dns berikut DNS c-mon.bankbsi.co. ... [Content truncated for display]`,
    mainCategory: 'Service Request',
    technicalCategory: 'DNS',
    priority: 'MEDIUM',
    status: 'OPEN',
    requester: 'Bank Syariah Indonesia (BSI)',
    requesterEmail: 'bsi-ops@bankbsi.co.id',
    assigneeId: 'usr-03',
    assigneeName: 'Ismail Ak (ismailak)',
    assignmentGroup: 'OP0899 - BSI DNS & DHCP Infoblox',
    createdAt: '2026-09-07T08:00:00.000Z',
    updatedAt: '2026-09-07T12:00:00.000Z',
    dueAt: '2026-09-08T08:00:00.000Z',
    slaHours: 24,
    slaStatus: 'SAFE',
    ruleEngineSuggested: {
      mainCategory: 'Service Request',
      technicalCategory: 'DNS',
      priority: 'MEDIUM',
      confidence: 96,
      matchedKeywords: ["dns", "a record", "infoblox"],
      explanation: "Matched 'Penambahan DNS' request. Categorized as DNS Request -> Sub-kriteria: A Record.",
    },
  },
  {
    id: 'tkt-otrs-29867',
    externalId: 'OTRS-2026050522000339',
    ticketNumber: '2026050522000339',
    kriteria: 'DNS Request',
    subKriteria: 'A Record',
    subject: "Fw: PERMOHONAN PENAMBAHAN DNS PADA SERVER LWMP ENVIRONMENT DEVELOPMENT & PRODUCTION",
    description: `Fw: PERMOHONAN PENAMBAHAN DNS PADA SERVER LWMP ENVIRONMENT DEVELOPMENT & PRODUCTION
[Article 66355]: P {margin-top:0;margin-bottom:0;} Dear rekan Integra, Mohon bantuannya untuk dibuatkan MoP terkait penambahan a record sesuai dengan dokumen terlampir. Best Regards, Bagas Pratama A Network Management Engineer E : bagas.pratama@bankbsi.co.id W: www.bankbsi.co.id PT. Bank Syariah Indonesia, Tbk. &nbsp; | Kantor Pusat Gedung The Tower &nbsp; | Jl. Gatot Subroto No. 27 Kelurahan Karet Semanggi, Kecamatan Setiabudi, Jakarta Selatan, DKI Jakarta 12930 Indonesia From: &nbsp;CHAIRINA MARSYA &lt;chairina.marsya@bankbsi.co.id&gt; Sent: &nbsp;Tuesday, May 5, 2026 5:43 PM To: &nbsp;IOG Network &lt;iog_network@bankbsi.co.id&gt; Cc: &nbsp;SUMINI WIJI LESTARI &lt;sumini.wiji@bankbsi.co.id&gt;; LAIL NUGRAHA PRATAMA &lt;lail.nugraha@bankbsi.co.id&gt; Subject: &nbsp;PERMOHONAN PENAMBAHAN DNS PADA SERVER LWMP ENVIRONMENT DEVELOPMENT &amp; PRODUCTION &nbsp; Salam tim @IOG Network , Bersama email ini kami mengajukan permohonan penambahan DNS pada server environment development &amp; production project LWMP, dengan detil IP &amp; DNS sebagai berikut: Nama DNS &nbsp; IP &nbsp; Port &nbsp; Kegunaan &nbsp; lwmp.bankbsi.co.id&nbsp; 10.0.16.69&nbsp; 443&nbsp; APP&nbsp;LWMP&nbsp;Production&nbsp; lwmp-db.bankbsi.co.id&nbsp; 10.0.32.191&nbsp; 3306&nbsp; DB&nbsp;LWMP&nbsp;Production&nbsp; lwmp-redis.bankbsi.co.id&nbsp; 10.0.32.191&nbsp; 6379&nbsp; Redis&nbsp;LWMP&nbsp;Production&nbsp; lwmp-dev.bankbsi.co.id&nbsp; 10.0.245.4&nbsp; 443&nbsp; APP LWMP&nbsp;Development&nbsp; lwmp-db-dev.bankbsi.co.id&nbsp; 10.0.246.4&nbsp; 3306&nbsp; DB&nbsp;LWMP&nbsp;Development&nbsp; lwmp-redis-dev.bankbsi.co.id&nbsp; 10.0.246.4&nbsp; 6379&nbsp; Redis&nbsp;LWMP&nbsp;Development&nbsp; Kami sertakan pula memo pengajuan D ... [Content truncated for display]`,
    mainCategory: 'Service Request',
    technicalCategory: 'DNS',
    priority: 'MEDIUM',
    status: 'OPEN',
    requester: 'Bank Syariah Indonesia (BSI)',
    requesterEmail: 'bsi-ops@bankbsi.co.id',
    assigneeId: 'usr-03',
    assigneeName: 'Ismail Ak (ismailak)',
    assignmentGroup: 'OP0968 - BSI - Infoblox DNS & DHCP DC2 Cibitung',
    createdAt: '2026-09-07T08:00:00.000Z',
    updatedAt: '2026-09-07T12:00:00.000Z',
    dueAt: '2026-09-08T08:00:00.000Z',
    slaHours: 24,
    slaStatus: 'SAFE',
    ruleEngineSuggested: {
      mainCategory: 'Service Request',
      technicalCategory: 'DNS',
      priority: 'MEDIUM',
      confidence: 96,
      matchedKeywords: ["dns", "a record", "infoblox"],
      explanation: "Matched 'Penambahan DNS' request. Categorized as DNS Request -> Sub-kriteria: A Record.",
    },
  }
];

export const SEED_WORKLOGS: Worklog[] = [
  {
    id: 'wl-01',
    ticketId: 'tkt-otrs-34988',
    ticketNumber: '2026090722000097',
    kriteria: 'DNS Request',
    subKriteria: 'CNAME',
    userId: 'usr-03',
    userName: 'Ismail Ak (ismailak)',
    userRole: 'engineer',
    date: '2026-09-07',
    startTime: '13:30',
    endTime: '14:45',
    description: 'Verified authoritative forward zone bankbsi.co.id. Configured CNAME record bridgecon.bankbsi.co.id and propagated to Infoblox grid members.',
    durationMinutes: 75,
    createdAt: '2026-09-07T14:45:00.000Z',
  },
  {
    id: 'wl-02',
    ticketId: 'tkt-otrs-34958',
    ticketNumber: '2026090722000033',
    kriteria: 'DNS Request',
    subKriteria: 'A Record',
    userId: 'usr-03',
    userName: 'Ismail Ak (ismailak)',
    userRole: 'engineer',
    date: '2026-09-07',
    startTime: '10:00',
    endTime: '11:30',
    description: 'Investigated DB ATM Monitoring server A-record mapping for DRC environment. Validated reverse PTR record consistency.',
    durationMinutes: 90,
    createdAt: '2026-09-07T11:30:00.000Z',
  },
];

export const SEED_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'aud-01',
    timestamp: '2026-09-07T20:25:13.000Z',
    userId: 'usr-03',
    userName: 'ismailak',
    role: 'engineer',
    action: 'OTRS_SYNC',
    module: 'Integration',
    entityId: 'OP0899 & OP0968',
    oldValue: '0 records',
    newValue: '26 live tickets imported from https://icare.lt-integra.com/otrs/index.pl',
    ipAddress: '192.168.15.73',
  },
];

export const SEED_INTEGRATION_CONFIG: IntegrationConfig = {
  providerName: 'iCare OTRS Portal (BSI DNS & DHCP Infoblox)',
  portalUrl: 'https://icare.lt-integra.com/otrs/index.pl',
  apiUrl: 'https://icare.lt-integra.com/otrs/nph-genericinterface.pl/Webservice/GenericTicketConnectorREST',
  authType: 'BASIC_AUTH',
  apiKeyOrToken: 'ismailak:••••••••••••',
  syncIntervalMinutes: 15,
  connectionStatus: 'CONNECTED',
  lastSyncAt: new Date().toISOString(),
  successRecordsCount: 26,
  failedRecordsCount: 0,
  isAutoSyncEnabled: true,
  mockPortalEnabled: false,
};

export const SEED_SYNC_LOGS: SyncLog[] = [
  {
    id: 'sync-01',
    timestamp: new Date().toISOString(),
    direction: 'INBOUND',
    status: 'SUCCESS',
    recordsCount: 26,
    message: 'Imported 25 tickets from OP0899 (BSI DNS & DHCP) and 1 ticket from OP0968 (Cibitung DC2).',
    durationMs: 742,
  },
];

export const SEED_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif-01',
    title: 'OTRS Live Sync Completed',
    message: 'Successfully pulled 26 tickets from queues OP0899 and OP0968 (BSI Infoblox DNS & DHCP).',
    type: 'NEW_TICKET',
    createdAt: new Date().toISOString(),
    read: false,
  },
];

export const DEFAULT_SLA_POLICY: SLAPolicyConfig = {
  CRITICAL: 4,
  HIGH: 8,
  MEDIUM: 24,
  LOW: 72,
};
